<html>
<head>
<meta name="layout" content="main" />
</head>
<body>
<div class="container">
	<div class="static-content">
	  <br>
	  <h1 > PRIVACY POLICY</h1>
	  <br/>
	  <h1 class="none-transform">Effective as of August 2013</h1>
	  <p class="static-content-paragraph"> We at Crowdera Inc. ("<u>Crowdera</u>") have created this privacy policy (this "<u>Privacy Policy</u>") because we know that you care about how information you provide to us is used and shared. This Privacy Policy relates to the information collection and use practices of Crowdera in connection with our Services, which are made available to you through the Platform.</p>
	  <p class="static-content-paragraph"> By visiting our Website and/or using our Services on the Platform, you are agreeing to the terms of this Privacy Policy and the accompanying Terms of Use. </p>
	  <p class="static-content-paragraph"> Capitalized terms not defined in this Privacy Policy shall have the meaning set forth in our Terms of Use. </p>
	  <p class="static-content-paragraph"> <b><u> The Information We Collect</u></b> </p>
	  <p class="static-content-paragraph"> <b><u>1.	Personal Information</u></b><br/>
	    When you sign up to become a Campaign Administrator or Supporter, enter any promotion, contest, or sweepstakes, or sign up for our newsletter or other publications, you will be required to provide us with personal information about yourself, which may include your name, address, e-mail address, and phone number. </p>
	  <p class="static-content-paragraph"> If you elect to sign in to the Platform using Facebook Connect or Twitter Connect, you are authorizing Crowdera to collect, store, and use, in accordance with this Privacy Policy, any and all information that you agreed that Facebook, Inc. ("<u>Facebook</u>") or Twitter, Inc. ("<u>Twitter</u>") could provide to Crowdera through Facebook's or Twitter's Application Programming Interface ("<u>API</u>").  Such information may include, without limitation, your first and last name, Facebook or Twitter username, Facebook or Twitter profile picture, unique Facebook or Twitter identifier and access token, and e-mail address.  Facebook Connect and Twitter Connect give you the option to post information about your activities on the Platform to your profile page to share with others within your network or opt out of information you do not wish to share. </p>
	  <p class="static-content-paragraph"> All information collected pursuant to this section is collectively referred to as "<u>Personal Information</u>."  We do not collect or access any Personal Information from you when you use the Services unless you provide us with the Personal Information voluntarily or authorize us to access it. </p>
	  <p class="static-content-paragraph"> <b><u>2.	Billing Information</u></b><br/>
	    When Supporters wish to make Donations or Contributions, they will be required to provide certain information in addition to the Personal Information noted above.  Such information may include a debit card number, credit card number, expiration date, bank account information, billing address, activation codes, and similar information.  Such information is collectively called the "<u>Billing Information</u>".  Donations and Contributions are collected and processed by our third-party vendor pursuant to the terms and conditions of its privacy policy, and we do not obtain access to any Billing Information in connection with these transactions.  We do, however, obtain access to Billing Information provided by Campaign Administrators, because we pay out the Net Proceeds and need access to this information to make the payments. </p>
	  <p class="static-content-paragraph"> <b><u>3.	Other Information</u></b><br/>
	    In addition to the Personal Information and Billing Information that you voluntarily provide to us, we may collect additional information (collectively, the "<u>Other Information</u>").  Such Other Information may include:
	  <ol class="static-page-ul clear">
	    <li class="static-page-li-order"> <u>From You</u>.  Additional information about yourself or your organization that you voluntarily provide to us, such as product and service preferences and other information that does not identify you personally. </li>
	    <li class="static-page-li-order"> <u>From Your Activity</u>.  Information that we automatically collect when you use the Services, including, without limitation:<br/>
	      <ul class="static-page-ul clear">
	        <li class="static-page-li"> IP addresses, browser type and language, referring and exit pages and URLs, date and time, amount of time spent on particular pages, sections of the Website visited, etc.; </li>
	        <li class="static-page-li">Information about a mobile device, including universally unique ID ("<u>UUID</u>"), Platform type and version (e.g., iOS or Android), carrier and country location, hardware and processor information (storage, chip speed, camera resolution, NFC enabled, and network type (WiFi, 2G, 3G, 4G); and</li>
	        <li class="static-page-li"> Activity and usage information occurring via the Services, including Campaign, Donation, and Contribution information, tagging data, favorites, survey responses, preferences, session lengths; and similar data. </li>
	      </ul>
	    </li>
	    <li class="static-page-li-order"> <u>From Cookies</u>.  Information that we collect using "cookie" technology.  Cookies are small packets of data that a website stores on your computer's or mobile device's hard drive so that your computer will "remember" information about your visit.  We may use both session cookies (which expire once you close your web browser) and persistent cookies (which stay on your computer until you delete them) to help us collect Other Information and to enhance your experience using the Platform.  If you do not want us to place a cookie on your hard drive, you may be able to turn that feature off on your computer or mobile device.  Please consult your Internet browser's documentation for information on how to do this and how to delete persistent cookies.  However, if you decide not to accept cookies from us, the Platform may not function properly. </li>
	    <li class="static-page-li-order"> <u>From Other Sources</u>.  Information that we collect or receive from Facebook, Twitter, and/or other third-party social media sites on which you have used the Services in accordance with their terms of use and privacy policies. </li>
	  </ol>
	  </p>
	  <p class="static-content-paragraph"> <b><u> Accessing and Modifying Personal Information and Communication Preferences</u></b> </p>
	  <p class="static-content-paragraph"> If you have registered for the Services, you may access, review, and make changes to your Personal Information, Billing Information, and certain Other Information by following the instructions found on the Platform.  In addition, you may manage your receipt of marketing and non-transactional communications by clicking on the "unsubscribe" link located on the bottom of any Crowdera marketing email.  We will use commercially reasonable efforts to process such requests in a timely manner.  You should be aware, however, that it is not always possible to completely remove or modify information in our subscription databases.  Campaign Administrators and Supporters cannot opt out of receiving transactional e-mails related to their account. </p>
	  <p class="static-content-paragraph"> <b><u> How We Use and Share the Information</u></b> </p>
	  <p class="static-content-paragraph"> We use the Personal Information, the Billing Information, and the Other Information to provide and improve the Platform and the Services, administer Campaigns, process Donations and Contributions, solicit your feedback, administer our perks, contests, and promotional programs, and inform you about our products and services and those of our third-party marketing partners and sponsors.  Also, we may share Personal Information, Billing Information, and/or Other Information as described below.<br/>
	  <ul class="static-page-ul clear">
	    <li class="static-page-li"> Any data and/or content that you post to the Platform will be publicly viewable on the Platform and shareable by other users.  Likewise, anything that you post to a social account (e.g., Facebook or Twitter) via the Platform will be viewable and accessible on those social accounts as if you had posted it on the social account directly.</li>
	    <li class="static-page-li"> In order to provide the Services and administer our perks and promotional programs, we may share your Personal Information and Other Information with our third-party promotional and marketing partners and sponsors, including, without limitation, business participating in our various programs.</li>
	    <li class="static-page-li"> In an ongoing effort to better understand our users and our Platform and Services, we might analyze the Other Information in aggregate form in order to operate, maintain, manage, and improve the Services and/or Platform.  This aggregate information does not identify you personally.  We may share this aggregate data with our affiliates, agents, and business partners.  We may also disclose aggregated user statistics in order to describe our products, Platform, and Services to current and prospective business partners and to other third parties for other lawful purposes.</li>
	    <li class="static-page-li">We may employ other companies and individuals to perform functions on our behalf.  Examples may include providing marketing assistance, information technology support, and customer service.  These other companies will have access to the Personal Information, the Billing Information, and the Other Information only as necessary to perform their functions and to the extent permitted by law. </li>
	    <li class="static-page-li">With your permission, third-party applications or services may access your Personal Information.  We use standard OAuth (open authorization) to enable you to give permission to share your Personal Information with other websites and services, such as Facebook and Twitter (e.g., when you agree to a pop-up requesting you to allow another application to access your account information).  We also use OAuth to allow us to share information about you that is stored by us without sharing your security credentials. </li>
	    <li class="static-page-li"> We may share some or all of your Personal Information, Billing Information, and Other Information with any of our parent companies, subsidiaries, joint ventures, or other companies under common control with us.</li>
	    <li class="static-page-li">As we develop our businesses, we might sell or buy businesses or assets.  In the event of a corporate sale, merger, reorganization, sale of assets, dissolution, or similar event, the Personal Information, Billing Information, and Other Information may be part of the transferred assets. </li>
	    <li class="static-page-li">To the extent permitted by law, we may also disclose Personal Information, Billing Information, and Other Information when required by law, court order, or other government or law enforcement authority or regulatory agency, or whenever we believe that disclosing the such information is necessary or advisable, for example, to protect the rights, property, or safety of Crowdera or others. </li>
	  </ul>
	  </p>
	  <p class="static-content-paragraph"> <b><u> How We Protect Your Information</u></b> </p>
	  <p class="static-content-paragraph"> We take commercially reasonable steps to protect the Personal Information, the Billing Information, and the Other Information from loss, misuse, and unauthorized access, disclosure, alteration, or destruction.  Please understand, however, that no security system is impenetrable.  We cannot guarantee the security of our databases, nor can we guarantee that the information you supply will not be intercepted while being transmitted to and from us over the Internet. In particular, e-mail sent to or from the Platform may not be secure, and you should therefore take special care in deciding what information you send to us via e-mail. </p>
	  <p class="static-content-paragraph"> <b><u>Important Notice to Non-U.S. Residents</u></b> </p>
	  <p class="static-content-paragraph"> It is important to note that the Platform and its servers are operated in the United States.  If you are located outside of the United States, please be aware that any Personal Information you provide to us will be transferred to the United States.  By using the Platform and by providing us Personal Information when using our Services, you hereby consent to this transfer and our use of the information and data provided by you in accordance with this Privacy Policy. </p>
	  <p class="static-content-paragraph"> <b><u>Children </u><u class="css-style-color">Online Privacy Protection Act (COPPA)</u></b> </p>
	  <p class="static-content-paragraph"> We do not knowingly collect Personal Information from children under the age of 13 through the Platform.  If you are under 13, please do not give us any Personal Information.  We encourage parents and legal guardians to monitor their children's Internet usage and to help enforce our Privacy Policy by instructing their children to never provide Personal Information through the Platform without their permission.  If you have reason to believe that a child under the age of 13 has provided Personal Information to us, please contact us, and we will endeavor to delete that information from our databases. </p>
	  <p class="static-content-paragraph"> <b><u>External Websites </u></b> </p>
	  <p class="static-content-paragraph"> The Platform may contain links to third-party websites.  Crowdera has no control over the privacy practices or the content of any of our business partners, advertisers, sponsors, or other websites to which we provide links.  As such, we are not responsible for the content or the privacy policies of those third-party websites.  You should check the applicable third-party privacy policy and terms of use when visiting any other websites. </p>
	  <p class="static-content-paragraph"> <b><u>Changes to This Privacy Policy </u></b> </p>
	  <p class="static-content-paragraph"> This Privacy Policy is effective as of the date stated at the top of this Privacy Policy.  We may change this Privacy Policy from time to time.  By accessing the Platform and/or using the Services after we make any such changes to this Privacy Policy, you are deemed to have accepted such changes.  Please be aware that, to the extent permitted by applicable law, our use of the Personal Information, the Billing Information, and the Other Information is governed by the Privacy Policy in effect at the time we collect the information.  Please refer back to this Privacy Policy on a regular basis </p>
	  <p class="static-content-paragraph"> <b><u>How to Contact Us </u></b> </p>
	  <p class="static-content-paragraph"> If you have questions about this Privacy Policy, please e-mail us at <small><a href="mailto:contact@crowdera.co" class="privacy-policy-css-color">contact@crowdera.co</a></small> or follow the instructions on the Platform. </p>
	  <br/>
	</div>
</div>
</body>
</html>
