<html>
<head>
<meta name="layout" content="main" />
</head>

<body>
<div class="container">
  <div class="static-content">
    </br>
    <h1 >TERMS AND CONDITIONS</h1>

    <p class="static-content-paragraph">Crowdera Inc.("Crowdera", "we", "us", or "our") welcomes you. We invite you to access and use our online services (the "Services"), which are made available to you through a variety of platforms, including http://www.crowdera.co (the "Website") and through our mobile app, which is accessible through tablets, cell phones, personal digital assistants, connected televisions, and other devices (the "App"). The Website and the App are collectively referred to as the "Platform".</p>
    <p class="static-content-paragraph">We provide our Services to Visitors, Campaign Administrators, and Supporters (as defined below) subject to the following Terms of Use, which may be updated by us from time to time without notice to you. By browsing the public areas or by accessing and using the Services, you acknowledge that you have read, understood, and agree to be legally bound by these Terms of Use and our Privacy Policy, which is hereby incorporated by reference (collectively, this "Agreement"). If you do not agree to any of these terms, then please do not use the Services.</p>
    <p class="static-content-paragraph">Capitalized terms not defined in these Terms of Use shall have the meaning set forth in our Privacy Policy.</p>
    <h2>1. DESCRIPTION AND USE OF SERVICES</h2>
    <p class="static-content-paragraph">Crowdera is a crowdfunding platform for people and organizations to raise money and support for charitable and good causes. Campaign administrators/creators working to drive their causes, enhance and improve the lives of people, enhance their communities, and those driving educational and/or cultural experience of youth can upload their Campaigns (as defined below) to the Platform , and Supporters from anywhere in the world can rally to fund and support the Campaign, with no fee paid to Crowdera</p>
    <p class="static-content-paragraph">We have gone to great lengths to create and foster a community of like-minded people who are dedicated to celebrating doing good who educate and inspire them. It is our intent to complement organization's existing fundraising and volunteering activities, and give individuals access to the ability to raise money by giving you access to a user-friendly Platform to create visually compelling, viral fundraising campaigns that raise awareness and funding for your organizational needs, causes, and dreams.</p>
    <p class="static-content-paragraph">We are here to help you get started or answer any question you may have regarding our Platform and Services. We will do our best to respond to your requests and answer questions as quickly as possible.</p>
    <p class="static-content-paragraph">We would like to point out, however, that although the Platform enables Supporters to make donations to 501(c)(3) companies, charities, and other nonprofit entities ("Donations") and contributions to certain for-profit entities ("Contributions"), we serve as an intermediary and not a party to any such Donations and Contributions. Accordingly, we shall have no liability to any party in connection with such Donations and Contributions, and our Campaign Administrators and Supporters acknowledge this when using the Platform.</p>
    <p class="static-content-paragraph">We provide Visitors, Campaign Administrators, and Supporters with access to the Platform as described in this Agreement.</p>
    <p class="static-content-paragraph"><u>Visitors.</u> Visitors, as the term implies, are people who don't login to the Platform or register with us, but want to look around and see what the Services are all about. Visitors can: (i) view all publicly-accessible content; and (ii) e-mail us.</p>
    <p class="static-content-paragraph"><u>Campaign Administrators.</u> Campaign Administrators are people and organizations who set up and create fundraisers, campaigns, scholarships, charities, and other Campaigns for social good. (each a "Campaign") on the Platform. Login is required for all Campaign Administrators, either through Facebook Connect, Twitter Connect, or pursuant to Section 6 below. Campaign Administrators can designate other  people within their organization (number of other administrators limited by the capabilities and functionality of the platform) to access the Platform and upload Campaign Content (as defined below). Campaign Administrators can do all the things that Visitors can do, and can: (i) create and set up a Campaign; (ii) upload updates, including blog posts, videos, photos, and other content regarding the Campaign (collectively, "Campaign Content"); (iii) connect their Campaign to their social networks and e-mail lists; (iv) provide feedback; and (v) sign up for alerts and other notifications.</p>
    <p class="static-content-paragraph"><u>Supporters.</u> Supporters are the lifeblood of the Platform, as they make the Donations and Contributions that support our Campaign Administrators. Login is required for all Campaign Administrators, either through Facebook Connect, Twitter Connect, or pursuant to Section 6 below.</p>
    <p class="static-content-paragraph">Although we encourage people to use our Platform, we are under no obligation to accept any individual as a Campaign Administrator or Supporter, and may accept,reject, or disable any login, registration, or Campaign in our sole and complete discretion at any time.</p>
    <h2>2. RESTRICTIONS</h2>
    <p class="static-content-paragraph">Becoming a Campaign Administrator is currently open to US and Canadian residents who are at least 18 years old. If you are under 18, please ask a teacher, parent teacher association ("PTA/PTO") representative, school administrator, teacher, or adult volunteer to support your efforts. Although our Platform has been created for use by parent volunteers, students, and teachers, we also welcome nonprofit supporting social good causes, education and those partnering with schools and organizations to upload Campaigns.</p>
    <p class="static-content-paragraph">Supporters can be from anywhere in the world, but must be at least the age of majority in their jurisdiction. If you are under the age of majority in your jurisdiction and would like to make a Donation or Contribution, you should review this Agreement with your parent or guardian to make sure that you and your parent or guardian understand and agree to it.</p>
    <h2>3. SAFETY OF CHILDREN AND CONFIDENTIALITY</h2>
    <p class="static-content-paragraph">THE SAFETY AND ENHANCEMENT OF CHILDREN IS OUR NUMBER ONE PRIORITY. SO, BEFORE YOU UPLOAD ANY CAMPAIGN CONTENT CONTAINING THE IMAGE OF OR INFORMATION ABOUT A CHILD, PLEASE DETERMINE WHETHER UPLOADING IT TO THE PLATFORM PASSES THE COMMON SENSE TEST. IN ADDITION, BEFORE UPLOADING ANY INFORMATION OR IMAGES OF ANOTHER PERSON'S CHILD, PLEASE OBTAIN THE CONSENT OF THAT CHILD'S PARENTS OR LEGAL GUARDIANS.</p>
    <p class="static-content-paragraph">ALTHOUGH WE ENCOURAGE CAMPAIGN ADMINISTRATORS TO CREATE AND UPLOAD CAMPAIGN CONTENT AND COMMUNICATE WITH US AND OTHER USERS, PLEASE NOTE THAT ANY IDEAS, CONTENT, AND INFORMATION YOU POST OR SHARE ON THE PLATFORM MAY BE SEEN AND USED BY OTHERS, AND Crowdera CANNOT GUARANTEE THAT OTHER USERS WILL NOT USE THOSE IDEAS, CONTENT, OR INFORMATION THAT YOU SHARE ON THE PLATFORM. THEREFORE, IF YOU HAVE ANY INFORMATION THAT YOU WOULD LIKE TO KEEP CONFIDENTIAL, DON'T WANT OTHERS TO USE, AND/OR THAT IS SUBJECT TO THIRD-PARTY RIGHTS THAT MAY BE INFRINGED BY YOUR SHARING IT, DO NOT POST IT ANYWHERE ON OR THROUGH THE PLATFORM. Crowdera IS NOT RESPONSIBLE FOR ANY USERS' MISUSE OR MISAPPROPRIATION OF ANY OPPORTUNITY, IDEA, CONTENT, OR INFORMATION YOU POST ON OR THROUGH THE PLATFORM.</p>
    <h2>4. DISCLAIMER</h2>
    <p class="static-content-paragraph">AS NOTED, ALTHOUGH YOU ARE ABLE TO FIND INFORMATION ABOUT CAMPAIGNS THROUGH OUR PLATFORM, WE ARE NOT A PARTY TO ANY DONATION OR CONTRIBUTION. ACCORDINGLY, WE SHALL HAVE NO LIABILITY TO ANY PARTY IN CONNECTION WITH ANY SUCH DONATIONS OR CONTRIBUTIONS.</p>
    <p class="static-content-paragraph">In addition:</p>
    <ul class="static-page-ul clear">
      <li class="static-page-li"> We make no attempt to confirm, and do not confirm, the purported identity of any of our Visitors, Campaign Administrators, or Supporters or perform any diligence on the nature, scope, legitimacy, or viability of any Campaign. You are solely responsible for determining the identity and suitability of other users whom you may contact by means of the Platform.</li>
      <li class="static-page-li">We make no representations, offer no assurances, and do not investigate any of our Visitors', Campaign Administrators', or Supporters' background, morality, character, actions, or demeanor, and you hereby acknowledge that you assume the risk of any encounter or interaction with such persons. We encourage all users to communicate directly with other users through the tools available on the Platform and to review their profile pages.</li>
      <li class="static-page-li">Although we reserve the right to do so, we typically do not verify information that Campaign Administrators submit to the Platform.</li>
      <li class="static-page-li">We do not endorse any Visitors, Campaign Administrators, Supporters, or Campaigns.</li>
      <li class="static-page-li">We make no, and hereby disclaim all, representations, warranties, claims, and assurances as to any Campaign.</li>
    </ul>
    <h2>5. COMMUNITY GUIDELINES</h2>
    <p class="static-content-paragraph">Crowdera's community, like any community, functions best when its users follow a few simple rules. By accessing the Platform and/or using the Services, you hereby agree to comply with these community guidelines (the "<u>Community Guidelines</u>") and that:</p>
    <ul class="static-page-ul clear">
      <li class="static-page-li">You will not use the Services for any unlawful purpose</li>
      <li class="static-page-li">Campaign Administrators will not offer any Campaigns that they do not own or have the right to offer;</li>
      <li class="static-page-li">Campaigns cannot involve, or offer as a reward, loans, pornography, alcohol, firearms, tobacco, energy foods or drinks, nutritional supplements, illegal services, or any items the sale of which is prohibited by applicable law, including, without limitation, the laws of the United States, <u style="color:red;">the State of California, or any other state or country of your residence;</u></li>
      <li class="static-page-li">Campaign Administrators cannot promise to donate all or any portion of the Donations or Contributions to a cause (i.e., Donations and Contributions must be used solely and exclusively for the Campaign as described on the Platform);</li>
      <li class="static-page-li">You will not submit false or misleading information, or submit or offer any Donation, Contribution, reward, or other pledge that you do not intend to honor;</li>
      <li class="static-page-li">You may not use the Services to engage in any commercial activities (other than in connection with Campaigns), including, without limitation, advertising or promoting a product, service, or company; or engaging in any pyramid or other multi-tiered marketing scheme;</li>
      <li class="static-page-li">You will not access the Platform or use the Services to collect any market research for a competing business;</li>
      <li class="static-page-li">You will not upload, post, e-mail, transmit, or otherwise make available any Campaign Content that:</li><ul>
      <li class="static-page-li">is false, deceptive, misleading, deceitful, misinformative, or constitutes a "bait and switch" offer;</li>
      <li class="static-page-li">infringes any copyright, trademark, right of publicity, or other proprietary rights of any person or entity;</li>
      <li class="static-page-li">is threatening, tortious, defamatory, libelous, indecent, obscene, pornographic, or invasive of another's privacy; promotes violence; constitutes hate speech; or endorses or opposes a political official or candidate;</li>
      <li class="static-page-li">discloses any sensitive information about another person, including that person's e-mail address, postal address, phone number, credit card information, or any similar information;</li></ul>
      <li class="static-page-li">You will not "stalk" or otherwise harass another;</li>
      <li class="static-page-li">You will not impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
      <li class="static-page-li">You will not cover, obscure, block, or in any way interfere with any safety features (e.g., report abuse button) on the Platform;</li>
      <li class="static-page-li">You will not take any action that imposes or may impose (in our sole discretion) an unreasonable or disproportionately large load on our technical infrastructure;</li>
      <li class="static-page-li">You will not use automated means, including spiders, robots, crawlers, data mining tools, or the like to download or scrape data from the Platform, except for Internet search engines (e.g., Google) and non-commercial public archives (e.g., archive.org) that comply with our robots.txt file;</li>
      <li class="static-page-li">You will not use any automated device or software that enables the submission of automatic postings on the Platform without human intervention or authorship, including, without limitation, the use of any such automated posting device in connection with bulk postings or for automatic submission of postings at certain times or intervals; and</li>
      <li class="static-page-li">You will not interfere with or attempt to interrupt the proper operation of the Services through the use of any virus, device, information collection or transmission mechanism, software or routine, or access or attempt to gain access to any data, files, or passwords related to the Services through hacking, password or data mining, or any other means.</li>
    </ul>
    <p class="static-content-paragraph">Please let us know about inappropriate content. If you find something that violates our Community Guidelines, please let us know, and we'll review it. We reserve the right, in our sole and absolute discretion, to deny you access to the Platform, or any portion of the Services, without notice, and to remove any content that does not adhere to these guidelines.</p>
    <h2>6. REGISTRATION PROCESS</h2>
    <p class="static-content-paragraph">If Campaign Administrators or Supporters do not log in to the Platform through Facebook Connect or Twitter Connect, we will ask them to create an account, which includes a sign-in name ("<u>Sign-In Name</u>"), a password ("<u>Password</u>"), and perhaps certain additional information that will assist in authenticating their identity when they log in in the future, such as an e-mail address ("<u>Unique Identifiers</u>"). When creating their account, Campaign Administrators and Supporters must provide true, accurate, current, and complete information. Each Sign-In Name and corresponding Password can be used by only one user. Campaign Administrators and Supporters are solely responsible for the confidentiality and use of their Sign-In Name, Password, and Unique Identifiers, as well as for any use, misuse, or communications entered through the Platform using one or more of them. Campaign Administrators and Supporters will promptly inform us of any need to deactivate a Password or Sign-In Name, or change any Unique Identifier. We reserve the right to delete or change any Password, Sign-In Name, or Unique Identifier at any time and for any reason. Crowdera will not be liable for any loss or damage caused by any unauthorized use of a Campaign Administrator's or Supporter's account.</p>
    <h2>7. CAMPAIGNS, DONATIONS, CONTRIBUTIONS, AND PAYMENTS TO CAMPAIGN ADMINISTRATORS</h2>
    <p class="static-content-paragraph"><u>Creating the Campaign.</u> As noted above, Campaign Administrators create Campaigns. To do so, a Campaign Administrator creates the profile of the Campaign, including describing the Campaign and any rewards being offered, establishing the duration of the Campaign (which cannot be longer than 90 days), setting the funding goal of the Campaign (the "<u>Goal</u>"), and linking the Campaign Administrator's payment account to the Platform. Once the Campaign Administrator has done these things, the Campaign can launch on the Platform.</p>
    <p class="static-content-paragraph"><u>Making Donations and Contributions.</u> We and our Campaign Administrators greatly appreciate your Donations and Contributions. You agree that when you make any Donation or Contribution our third-party payment processor may immediately authorize and charge your credit card (or other approved facility) for the Donation or Contribution.</p>
    <p class="static-content-paragraph">In addition, we need to be clear that: <u><b>(i) except as provided in the immediately next paragraph, Contributions and Donations made via the Platform are non-refundable; (ii) unless otherwise stated by the applicable Campaign Administrator solely with respect to Donations for a specific Campaign, Donations and Contributions are not tax deductible; (iii) if a particular Donation is tax deductible, the applicable Campaign Administrator shall be responsible for providing the Supporters receipts and acknowledgments of the Donation; and (iv) Crowdera shall have no liability for any claims by any taxing authority with respect to any characterizations made by Supporters regarding the deductibility of any Contribution or Donations on any state or federal tax return.</b></u> Also, as noted above, all Donations and Contributions are processed through our third-party payment processors. By executing any Donation or Contribution through such third-party vendors, Supporters are also agreeing to their terms of use and privacy policies. If Supporters have questions about any charges on their credit cards, debit cards, or other statements, they should contact the applicable third-party vendor listed on the Platform.</p>
    <p class="static-content-paragraph">Notwithstanding subparagraph (i) above, Campaign Administrators reserve the right to refund Donations and Contributions (less our Administrative Fee and the Processing Fees, as defined below) on a case by case basis. Such refunds, if available, are handled exclusively by the applicable Campaign Administrator, and Crowdera is not responsible for handling or communicating your request to the Campaign Administrator. Campaign Administrators agree that they are solely responsible for providing information concerning their refund policies on the Campaign page. If a Supporter wishes to seek a refund, he or she must communicate directly with the Campaign Administrator using the e-mail on the Campaign page. Should a Subscriber have difficulty locating the Campaign Administrator's contact information, please contact our crew at hello@ crowdera.co for assistance.</p>
    <p class="static-content-paragraph"><u> Payments to Campaign Administrators.</u> When a Supporter makes a Donation or Contribution, the payment is processed through our third-party payment vendor and released to the applicable Campaign Administrator's designated account within fourteen (14) days of the close of the Campaign less: (i) Crowdera's administrative fee("<u>Administrative Fee</u>"), as set forth on the Platform, and (ii) the fees charged by the applicable third-party payment vendor (the "<u>Processing Fees</u>"), which may vary depending on any number of factors (the net amount hereinafter referred to as the <u>Net Proceeds</u>). </p>
    <p class="static-content-paragraph">Please note that we are <u><b>not</b></u> an "<u>all or nothing</u>" crowdfunding portal, and Campaign Administrators will be paid their Net Proceeds regardless of whether their Goal has been achieved.</p>
    <p class="static-content-paragraph">Supporters and Campaign Administrators hereby release Crowdera from liability for delays or errors in connection with any third-party payment processors' processing of Donations and/or Contributions, including, but not limited to, any errors resulting from any inaccurate or outdated account information provided by Campaign Administrators. Supporters should confer with their tax advisors regarding the taxability of Donations and Contributions, and Campaign Administrators are solely responsible for ensuring that they comply with any obligations to pay any taxes or governmental charges in connection with any Donations and Contributions they receive.</p>
    <p class="static-content-paragraph"><u>Distribution of Rewards.</u> Campaign Administrators shall be solely responsible, at their expense, for honoring and distributing to Supporters any rewards offered in connection with a Campaign promptly after the close of the Campaign. Any sponsors that have offered their own promotion in connection with a Campaign shall be responsible for fulfilling their obligations as set forth in the applicable promotion.</p>
    <h2>8. INTELLECTUAL PROPERTY</h2>
    <p class="static-content-paragraph">The Platform contains material, such as software, text, graphics, images, sound recordings, audiovisual works, and other material provided by or on behalf of Crowdera (collectively referred to as the "Content"). The Content may be owned by us or by third parties. The Content is protected under both United States and foreign laws. Unauthorized use of the Content may violate copyright, trademark, and other laws. You have no rights in or to the Content, and you will not use the Content except as permitted under this Agreement. No other use is permitted without prior written consent from us. You must retain all copyright and other proprietary notices contained in the original Content on any copy you make of the Content. You may not sell, transfer, assign, license, sublicense, or modify the Content or reproduce, display, publicly perform, make a derivative version of, distribute, or otherwise use the Content in any way for any public or commercial purpose. The use or posting of the Content on any other website or in a networked computer environment for any purpose is expressly prohibited.</p>
    <p class="static-content-paragraph">If you violate any part of this Agreement, your permission to access and/or use the Content and the Platform automatically terminates, and you must immediately destroy any copies you have made of the Content.</p>
    <p class="static-content-paragraph">The trademarks, service marks, and logos of Crowdera ("<u>Crowdera Trademarks</u>") used and displayed on the Platform are registered and unregistered trademarks or service marks of Crowdera. Other company, product, and service names located on the Platform may be trademarks or service marks owned by others (the "<u>Third-Party Trademarks</u>", and, collectively with Crowdera Trademarks, the "<u>Trademarks</u>"). Nothing on the Platform or Services should be construed as granting, by implication, estoppel, or otherwise, any license or right to use the Trademarks, without our prior written permission specific for each such use. Use of the Trademarks as part of a link to or from any site is prohibited unless establishment of such a link is approved in advance by us in writing. All goodwill generated from the use of Crowdera Trademarks inures to our benefit.</p>
    <p class="static-content-paragraph">Elements of the Platform are protected by trade dress, trademark, unfair competition, and other state and federal laws and may not be copied or imitated, in whole or in part, by any means, including but not limited to the use of framing or mirrors. None of the Content may be retransmitted outside the Platform without our express, written consent for each and every instance.</p>
    <h2>9. COMMUNICATIONS TO US; CAMPAIGN CONTENT</h2>
    <p class="static-content-paragraph">Although we encourage you to e-mail us, we do not want you to, and you should not, e-mail us any content that contains confidential information. With respect to all e-mails you send to us, including but not limited to, feedback, questions, comments, suggestions, and the like, we shall be free to use any ideas, concepts, or techniques contained in your communications for any purpose whatsoever, including, but not limited to, the development, production, and marketing of products and services that incorporate such information, without compensation to you.</p>
    <p class="static-content-paragraph">As noted above, the Platform provides Campaign Administrators the ability to post and upload Campaign Content. You expressly acknowledge and agree that once you submit your Campaign Content for inclusion into the Services, it will be accessible by others, and that there is no confidentiality or privacy with respect to such Campaign Content, including, without limitation, any personally identifying information that you may make available. YOU, AND NOT Crowdera, ARE ENTIRELY RESPONSIBLE FOR ALL THE CAMPAIGN CONTENT THAT YOU UPLOAD, POST, E-MAIL, OR OTHERWISE TRANSMIT VIA THE PLATFORM.</p>
    <p class="static-content-paragraph">You retain all copyrights and other intellectual property rights in and to your own Campaign Content. You do, however, hereby irrevocably grant us and our sublicensees and assignees a non-exclusive, transferable, perpetual, royalty-free, freely sublicensable (through multiple tiers) license to modify, compile, combine with other content, copy, record, synchronize, transmit, translate, format, distribute, publicly display, publicly perform, and otherwise use or exploit (including for profit) any and all of your Campaign Content that you have not designated as private, your username, the picture associated with your username, and all intellectual property and moral rights therein throughout the universe, in each case, by or in any means, methods, media, or technology now known or hereafter devised. Without limiting the foregoing, you acknowledge and agree that uses of your Campaign Content, username, and associated picture permitted by the foregoing rights and licenses may include the display of such Campaign Content, username, and associated picture adjacent to advertising and other material or content, including for profit.</p>
    <p class="static-content-paragraph">Ownership of and licenses to Campaign Content submitted in connection with a particular contest shall be governed by the contest rules applicable to that contest. In connection with any such contest, if there is a conflict between those contest rules and these Terms of Use, the contest rules shall govern.
      If you submit Campaign Content to us, each such submission constitutes a representation and warranty to Crowdera that such Campaign Content is your original creation (or that you otherwise have the right to provide the Campaign Content), that you have the rights necessary to grant the license to the Campaign Content under the prior paragraph and that it and its use by Crowdera and its content partners as permitted by this Agreement does not and will not infringe or misappropriate the intellectual property, privacy, publicity, or moral rights of any person or contain any libelous, defamatory, or obscene material or content that violates our Community Guidelines.</p>
    <h2>10. NO WARRANTIES; LIMITATION OF LIABILITY</h2>
    <p class="static-content-paragraph">AS NOTED ABOVE, WE MAKE NO ATTEMPT TO CONFIRM, AND DO NOT CONFIRM, THE PURPORTED IDENTITY OF ANY VISITOR, CAMPAIGN ADMINISTRATOR, OR SUPPORTER, PERFORM NO DILIGENCE ON CAMPAIGNS, AND DO NOT WARRANT THAT THE DONATIONS OR THE CONTRIBUTIONS WILL BE USED FOR ANY PARTICULAR PURPOSE. SUPPORTERS ARE SOLELY RESPONSIBLE FOR DETERMINING THE IDENTITY AND SUITABILITY OF CAMPAIGN ADMINISTRATORS TO WHOM THEY MAY MAKE A DONATION OR CONTRIBUTION VIA THE PLATFORM. IF YOU HAVE ANY RESERVATIONS REGARDING THE IDENTITY OF A CAMPAIGN ADMINISTRATOR OR THE LEGITIMACY OF A PARTICULAR CAMPAIGN, DO NOT DONATE OR CONTRIBUTE. WE MAKE NO REPRESENTATIONS, OFFER NO ASSURANCES, AND DO NOT INVESTIGATE ANY OF OUR USERS' BACKGROUNDS, MORALITY, CHARACTER, OR ACTIONS, AND YOU HEREBY ACKNOWLEDGE THAT YOU ASSUME THE RISK OF ANY ENCOUNTER OR INTERACTION WITH SUCH PERSONS. WE ENCOURAGE ALL USERS TO COMMUNICATE DIRECTLY WITH CAMPAIGN ADMINISTRATORS THROUGH THE TOOLS AVAILABLE ON THE PLATFORM AND TO REVIEW THEIR PROFILE PAGES. ALTHOUGH WE RESERVE THE RIGHT TO DO SO, WE TYPICALLY DO NOT VERIFY INFORMATION THAT CAMPAIGN ADMINISTRATORS SUBMIT TO THE PLATFORM. WE DO NOT ENDORSE ANY USERS OR CAMPAIGNS.</p>
    <p class="static-content-paragraph">THE PLATFORM, THE SERVICES, AND THE CONTENT ARE PROVIDED ON AN AS IS AND AS AVAILABLE' BASIS WITHOUT ANY WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE WARRANTY OF TITLE, MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTIES' RIGHTS, AND FITNESS FOR PARTICULAR PURPOSE. YOU AGREE THAT YOU USE THE PLATFORM, THE SERVICES, AND THE CONTENT AT YOUR OWN RISK. WITHOUT LIMITING THE FOREGOING, WE DO NOT WARRANT THAT THE PLATFORM OR THE SERVICES WILL OPERATE ERROR-FREE OR THAT THE PLATFORM, THE SERVICES, THEIR SERVERS, OR CONTENT ARE FREE OF COMPUTER VIRUSES OR SIMILAR CONTAMINATION OR DESTRUCTIVE FEATURES. IF YOUR USE OF THE PLATFORM, THE SERVICES, OR THE CONTENT RESULTS IN THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA, WE SHALL NOT BE RESPONSIBLE FOR THOSE COSTS.</p>
    <p class="static-content-paragraph">IN NO EVENT SHALL WE BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL AND CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) RESULTING FROM DONATIONS OR CONTRIBUTIONS MADE VIA THE PLATFORM OR YOUR USE OR INABILITY TO USE THE PLATFORM, THE SERVICES, OR THE CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME STATES DO NOT ALLOW EXCLUSION OF IMPLIED WARRANTIES OR LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. IN SUCH STATES, OUR LIABILITY SHALL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.</p>
    <h2>11. EXTERNAL SITES</h2>
    <p class="static-content-paragraph">The Platform may contain links to third-party websites ("External Sites"). These links are provided solely as a convenience to you and not as an endorsement by us of the content on such External Sites. The content of such External Sites is developed and provided by others. You should contact the site administrator or webmaster for those External Sites if you have any concerns regarding such links or any content located on such External Sites. We are not responsible for the content of any linked External Sites and do not make any representations regarding the content or accuracy of materials on such External Sites. You should take precautions when downloading files from all websites to protect your computer from viruses and other destructive programs. If you decide to access linked External Sites, you do so at your own risk.</p>
    <h2> 12. REPRESENTATIONS; WARRANTIES; AND INDEMNIFICATION</h2>
    <ol class="static-page-ul clear">
      <li class="static-page-li-order">You hereby represent, warrant, and covenant that
        <ul class="static-page-ul clear">
          <li class="static-page-li">You own or have the necessary licenses, rights, consents, and permissions to all trademark, trade secret, copyright, or other proprietary, privacy, and publicity rights in and to your Campaign Content and any other works that you incorporate into your Campaign Content, and all the rights necessary to grant the licenses and permissions you grant hereunder;</li>
          <li class="static-page-li">Use of your Campaign Content in the manner contemplated in this Agreement shall not violate or misappropriate the intellectual property, privacy, publicity, contractual, or other rights of any third party; and</li>
          <li class="static-page-li">You shall not submit to the Platform any Campaign Content that violates our Community Guidelines set forth above.</li>
        </ul>
      </li>
      <li class="static-page-li-order">You agree to defend, indemnify, and hold us and our officers, directors, employees, agents, successors, licensees, sponsors, and assigns harmless from and against any claims, actions, or demands, including, without limitation, reasonable legal and accounting fees, arising or resulting from: (i) your breach of this Agreement; (ii) your access to, use, or misuse of the Content, the Campaign Content, the Platform, or the Services, and (iii) your violation, misappropriation, or infringement of any third-party right, including without limitation any copyright, trademark, property, publicity, or privacy right. We shall provide notice to you of any such claim, suit, or proceeding and shall assist you, at your expense, in defending any such claim, suit, or proceeding. We reserve the right to assume the exclusive defense and control of any matter that is subject to indemnification under this section. In such case, you agree to cooperate with any reasonable requests assisting our defense of such matter.</li>
    </ol>
    <h2>13. COMPLIANCE WITH APPLICABLE LAWS</h2>
    <p class="static-content-paragraph">The Platform is based in the United States. We make no claims concerning whether the Content may be downloaded, viewed, or be appropriate for use outside of the United States. If you access the Platform, the Services, or the Content from outside of the United States, you do so at your own risk. Whether inside or outside of the United States, you are solely responsible for ensuring compliance with the laws of your specific jurisdiction.</p>
    <h2>14. TERMINATION OF THE AGREEMENT</h2>
    <p class="static-content-paragraph">We reserve the right, in our sole discretion, to restrict, suspend, or terminate this Agreement, any Campaign, and your access to all or any part of the Platform, at any time and for any reason without prior notice or liability. We reserve the right to change, suspend, or discontinue all or any part of the Services at any time without prior notice or liability.</p>
    <h2>15. DIGITAL MILLENNIUM COPYRIGHT ACT</h2>
    <p class="static-content-paragraph">Crowdera respects the intellectual property rights of others and attempts to comply with all relevant laws. We will review all claims of copyright infringement received and remove any Content or Campaign Content deemed to have been posted or distributed in violation of any such laws.</p>
    <p class="static-content-paragraph">Our designated agent under the Digital Millennium Copyright Act (the "Act") for the receipt of any Notification of Claimed Infringement which may be given under that Act is as follows:</p>
    <p class="static-content-paragraph">Crowdera InC<br />
      Attention: DMCA<br />
      228 Hamilton Ave Floor 3<br />
      Menlo Park CA 94301<br>
    <u class="termofuse-style"><small><a href="mailto:contact@crowdera.co">contact@crowdera.co</a></small></u></p>
    <p class="static-content-paragraph">If you believe that your work has been copied on the Platform in a way that constitutes copyright infringement, please provide our agent with notice in accordance with the requirements of the Act, including: (i) a description of the copyrighted work that has been infringed and the specific location on the Platform where such work is located; (ii) a description of the location of the original or an authorized copy of the copyrighted work; (iii) your address, telephone number and e-mail address; (iv) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; (v) a statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf; and (vi) an electronic or physical signature of the owner of the copyright or the person authorized to act on behalf of the owner of the copyright interest.</p>
    <h2>16. MISCELLANEOUS</h2>
    <p class="static-content-paragraph">This Agreement is governed by the internal substantive laws of the State of California, without respect to its conflict of laws provisions. You expressly agree: (i) to submit to the exclusive personal jurisdiction of the state and federal courts sitting in the State of New Jersey; and (ii) that the Services shall be deemed passive that do not give rise to personal jurisdiction over Crowdera, either specific or general, in jurisdictions other than New Jersey. YOU AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE PLATFORM, THE SERVICES, THE CAMPAIGNS, THE DONATIONS, THE CONTRIBUTIONS, THE CONTENT, OR OTHERWISE ARISING UNDER THIS AGREEMENT MUST BE COMMENCED BY YOU WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE SUCH CAUSE OF ACTION IS PERMANENTLY BARRED. If any provision of this Agreement is found to be invalid by any court having competent jurisdiction or terminated in accordance with the Termination provision above, the invalidity or termination of such provision shall not affect the validity of the following provisions of this Agreement, which shall remain in full force and effect: "Safety of Children and Confidentiality", "Disclaimer", "Campaigns, Donations, Contributions, and Payments to Campaign Administrators", "Intellectual Property", "Communications to Us; Campaign Content", "No Warranties; Limitation of Liability", "Representations; Warranties; Indemnification", "Termination of the Agreement", and "Miscellaneous".</p>
    <p class="static-content-paragraph"><h6>Our failure to act on or enforce any provision of the Agreement shall not be construed as a waiver of that provision or any other provision in this Agreement. No waiver shall be effective against us unless made in writing, and no such waiver shall be construed as a waiver in any other or subsequent instance. Except as expressly agreed by us and you in writing, this Agreement constitutes the entire Agreement between you and us with respect to the subject matter, and supersedes all previous or contemporaneous agreements, whether written or oral, between the parties with respect to the subject matter. The section headings are provided merely for convenience and shall not be given any legal import. This Agreement will inure to the benefit of our successors, assigns, licensees, and sublicensees.</h6></p>
  </div>
</div>
</body>
</html>
