<g:set var="projectService" bean="projectService"/>
<%
	def currentEnv = projectService.getCurrentEnvironment()
	def country_code = projectService.getCountryCodeForCurrentEnv(request)
%>
<html>
<head>
<meta name="layout" content="main" />
<title>Crowdera- Universal Terms of Service</title>
</head>

<body>
<div class="container term-use-container">
 <div class="static-content">
    <br><br>
    <h1>Universal Terms of Service</br>
    </br>
    Crowdera Inc</h1>
    <p class="static-content-paragraph"><b>PLEASE READ THIS UNIVERSAL TERMS OF SERVICE AGREEMENT CAREFULLY, AS IT CONTAINS IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS AND REMEDIES.
    </b></p>
    <h1>GENERAL TERMS AND CONDITIONS </h1>

    <p class="static-content-paragraph">Crowdera Inc. (referred to throughout as "Crowdera", "we", "us", or "our") is the owner and operator of 
				the www.gocrowdera.com website, an online fundraising platform for global nonprofit, for-profit and 
				individual entities raising money for  charitable, civic, social & personal causes. This agreement applies 
				to the www.gocrowdera.com website, any subdomains thereof, any API integrations or widgets we offer, and 
				any other website or webpages we own or operate that include a link to this statement (together collectively 
				referred to as the "Website"). Crowdera provides its services (described below) to you through its Website and 
				mobile applications (together collectively referred to as the "Platform") and related services (collectively, 
				such services, including any new features and applications, and the Platform, the "Services"), subject to the these
				Terms of Service(as amended from time to time). Any party that accesses, uses, or registers with the Platform
				(such party referred to throughout in the second person " you," "your," etc.) agrees to be contractually bound by 
				these Terms of Service, our Privacy Policy, all applicable laws and all conditions or policies referenced here 
				(collectively, the "Terms"). If you are a Fundraiser (as defined below) based in the United States you will be 
				contracting with Crowdera, Inc and if you are a Fundraiser based outside the United States please see the 
				INTERNATIONAL USE clause in this agreement.</p>
    <p class="static-content-paragraph">Your use of the Platform, or any of the services or features accessible therein, constitutes your acceptance of Terms. If you do not wish to use the Platform in accordance with the Terms, then you should immediately discontinue using the Platform.</p>
    <h2>UPDATES TO THE TERMS</h2>
    <p class="static-content-paragraph">We may update or change the Terms from time to time and We reserve the right, at our sole discretion, to change or modify portions of these Terms of Service at any time. Amendments will only apply prospectively. A given amendment will not apply to claims arising before, or arising from facts occurring before, the point in time when that amendment was published to the Platform. We will let you know that the Terms have been updated or changed by publishing the date of the last amendment at the top of this page. You agree that this method of notice is sufficient and that you will regularly check these Terms for updates or changes. Your continued use of the Services after the date any such changes become effective constitutes your acceptance of the new Terms of Service. If you do not wish to accept the new Terms of Service, you may discontinue your use of the Services.
	</p>
    <h2>INTELLECTUAL PROPERTY</h2>
    <p class="static-content-paragraph"><b>IP Protection.</b> The Platform, its forward facing components (images, designs, text, arrangements of the foregoing, etc.), its various features and services, and all underlying software and code belong exclusively to us. You understand and agree that your use of the Platform in no way gives you a right, title, or interest in the Platform or our intellectual property. The Platform and its various component parts are protected by copyright law, trademark law, trade secret law, and other laws germane to the protection of intellectual property rights.
	</p>
    <p class="static-content-paragraph"><b>Prohibited Activities.</b> You agree to use the Platform and the features and services provided through the Platform only as they are obviously intended to be used. All other uses are strictly prohibited. You agree not to (and not to encourage a third party to) disassemble, reverse engineer, or otherwise attempt to discover, copy, or transmit, any source code underlying the Platform or the software, features, or services provided therein.</p>
    <p class="static-content-paragraph"><b>Your Content.</b> By posting, uploading, or transmitting content or information to, or through, the Platform you grant us a nonexclusive, irrevocable, worldwide, sub-licensable (through multiple-tiers), royalty-free license to copy, store, transmit, publish, publicly display, publicly perform, and otherwise use this content or information to operate the Platform as we reasonably see fit. You warrant that you have the authority to grant such license.
	</p>
    
    <h2>USER WARRANTIES</h2>
    <p class="static-content-paragraph">By accessing, using, or registering with the Platform you represent, warrant, and irrevocably covenant that:
	</p>
	<ol class="IN-TW-terms-use-ol-num">
      <li>You have the authority to enter into this agreement.</li>
      <li>Your decision to enter into this agreement and your use of the Platform will not violate any applicable law, regulation, or ordinance.</li>
      <li>Your decision to enter into this agreement and your use of the Platform will not infringe the rights of any third parties.</li>
      <li>You will at all times supply truthful and accurate information to us and you will not misrepresent yourself to the public through your use of the Platform.</li>
	  <li>You will never use the Platform, or any services we provide to you, in a manner that violates the law or the legal rights of a third party.</li>
      <li>You are over the age of majority in the jurisdiction in which you live (i.e. at least 18, and in some cases 19) or, if you are a minor over the age of 13, you may only use the Platform with the permission and supervision of your parent or legal guardian</li>
      <li>You are not using another member’s account without her/his permission.</li>
      <li>You have not have been previously restricted, suspended or terminated by us</li>
    </ol>  
	
    <h2>INTERNATIONAL USE</h2>
    <p class="static-content-paragraph">The Service is controlled, operated and administered by Crowdera from our offices within the USA. If you access the Service from a location outside the USA, you are responsible for compliance with all local laws. If you are a Fundraiser based outside the United States but not within any of the countries sanctioned by OFAC, you will be contracting with Crowdera, Inc. If you are a Fundraiser (as defined below) based in the India you will be contracting with Crowdera Ventures India Pvt. Ltd. Access to the Platform and services from territories where the Platform and/or services are illegal is strictly prohibited. Users are responsible for complying with all local rules, laws, and regulations regarding their use of the Platform and services.</p>
    
    <h1>ACCESS OF PLATFORM AND USE OF SERVICES</h1>
    <p class="static-content-paragraph">Crowdera is an online fundraising platform for global nonprofit organizations, for profit businesses and individuals raising money for  charitable, social & personal causes. Fundraisers/creators working to drive their causes, follow their creative passion, enhance and improve the lives of people, enhance their communities, and those driving educational and/or cultural experience of youth can upload their Campaigns (as defined below) to the Platform, and Donors from anywhere in the world can rally to fund and support the Campaign. We have gone to great lengths to create and foster a community of like-minded people who are dedicated to celebrating doing good who educate and inspire them. It is our intent to complement organization's existing fundraising and volunteering activities, and give individuals access to the ability to raise money by giving you access to a user-friendly Platform to create visually compelling, viral fundraising campaigns that raise awareness and funding for your organizational needs, causes, and dreams. We are here to help you get started or answer any question you may have regarding our Platform and Services. We will do our best to respond to your requests and answer questions as quickly as possible.
	</p>
    <h2>DESCRIPTION OF SERVICES</h2>
    <p class="static-content-paragraph">The Services are offered as a platform to users of the Services, which may include Fundraisers and Donors (each defined herein) and other registered users of the Services (which may include users who simply "like" Campaigns or otherwise interact with the Platform or Services). Among other features, the Services are designed to allow a user (a "Fundraiser") to post a fundraising campaign ("Campaign") to the Platform to accept monetary donations ("Donations") from those registered users wishing to donate funds to the Campaign ("Donors"). For purposes hereof, the term "Fundraiser" shall also be deemed to include any individual(s) designated as a Fundraiser of a Campaign. </p>
    <h2>CAMPAIGNS</h2>
    <p class="static-content-paragraph">Fundraisers hosting Campaigns on the platform are not necessarily charities to which you can make tax-deductible charitable donations. Although the Platform enables Donors to make donations to American nonprofit organizations via registered as 501(c)(3); Indian Trusts, Societies, NGOs, and other nonprofit organizations registered via 80G, 12A, 35AC, 80CCC, 80U, 115A, 115AB, 115AC, 115AD & 115D; UK Registered Charity tax exempt via HMRC, Canada Charity approved by CRA; and other international non profits, charities, other nonprofit entities, certain for-profit or individual entities, ("Donations"), we serve as an intermediary and not a party to any such Donations. Any donation you make to a Charity through the Platform will be subject to a payment gateway transaction fee as described at https://gocrowdera.com/pricing. You understand and acknowledge, however, that Crowdera is not a charity. We are not a Broker, Financial Institution, Creditor or Charitable Institution: The Services are an administrative platform only. Accordingly, we shall have no liability to any party in connection with such Donations and donations, and our Fundraisers and Donors acknowledge this when using the Platform.
	</p>
    <p class="static-content-paragraph">Crowdera facilitates the Donation transaction between Fundraisers and Donors, but is not a party to any agreement between a Fundraiser and a Donor, or between any user and a Charity. Crowdera is not a broker, agent, financial institution, creditor or insurer for any user. Crowdera has no control over the conduct of, or any information provided by, a Fundraiser, and Crowdera hereby disclaims all liability in this regard to the fullest extent permitted by applicable law.
	</p>
    <p class="static-content-paragraph">Crowdera does not guarantee that a Campaign will obtain a certain amount of Donations or any Donations at all. We do not personally endorse any Campaign or Fundraiser, and we make no guarantee, explicit or implied, that any information provided through the Services by a user is accurate. We expressly disclaim any liability or responsibility for the success of any Campaign, or the outcome of any fundraising purpose. You, as a Donor, must make the final determination as to the value and appropriateness of contributing to any Campaign, or Fundraiser.
	</p>
    <p class="static-content-paragraph">We do not and cannot verify the information that Fundraisers supply, nor do we guarantee that the Donations will be used in accordance with any fundraising purpose prescribed by a Fundraiser. We assume no responsibility to verify whether the Donations are used in accordance with any applicable laws; such responsibility rests solely with the Fundraiser, as applicable. While we have no obligation to verify that the use of any funds raised is in accordance with applicable law and these Terms of Service, we take possible fraudulent activity and the misuse of funds raised very seriously. If you have reason to believe that a Fundraiser or Charity is not raising or using the funds for their stated purpose, please reach out to the Fundraiser directly and send us an email via our help desk to alert our team of this potential issue and we will investigate.
	</p>
    
    <h2>PERKS</h2>
    <p class="static-content-paragraph">Fundraisers can offer gifts or rewards in the form of tangible items or intangible services (collectively, "Perks") to Donors. Perks are not offered for sale. Crowdera makes no representations about the quality, safety, morality or legality of any Campaign, Perk or donations or the truth or accuracy of User Content (as defined below) posted on the Services. Crowdera does not represent that Fundraisers will deliver Perks or that donations will be used as described in the Campaign. Users use the Services at their own risk. Fundraisers are not permitted to offer or provide any of the following as a Perk:
	</p>
	<ol class="IN-TW-terms-use-ol-disc">
      <li>any form of "security" (as such term is defined in the United States Securities Act of 1933);</li>
      <li>any form of financial incentive or participation in any profit sharing;</li>
      <li>any alcoholic consumer products (vouchers or memberships offering physical delivery of alcoholic consumer products are permitted);</li>
      <li>any controlled substance, tobacco or drug paraphernalia;</li>
	  <li>any weapons, ammunition and related accessories;</li>
      <li>any energy foods, drinks or nutritional supplements;</li>
      <li>any form of lottery or gambling;</li>
      <li>any human remains, such as bones or skulls;</li>
      <li>any form of air transportation;</li>
      <li>any items the sale of which is prohibited by applicable law, including, without limitation, the laws of the United States, the State of California, or any other state or country of your residence; </li>
      <li>any items promoting hate, discrimination, personal injury, death, damage, or destruction to property; or any items (a) prohibited by applicable law to possess or distribute, (b) that would violate applicable law if distributed, or (c) that would result in infringement or violation of another person's rights if distributed.</li>
    </ol>
    <p class="static-content-paragraph"><b>Distribution of Perks.</b> Fundraisers shall be solely responsible, at their expense, for honoring and distributing to Contributors any perks offered in connection with a Campaign promptly after the close of the Campaign. Any sponsors that have offered their own promotion in connection with a Campaign shall be responsible for fulfilling their obligations as set forth in the applicable promotion.
	</p>
    <h2>TAXES</h2>
    <p class="static-content-paragraph"> It is your responsibility to determine what, if any, taxes apply to the Donations you receive through your use of the Services. It is solely your responsibility to assess, collect, report or remit the correct tax, if any, to the appropriate tax authority.
	</p>
    <h2>SECURITY AND ACCESS</h2>
    <p class="static-content-paragraph">Crowdera reserves the right to modify, suspend or discontinue, temporarily or permanently, the Services (or any part thereof). We will endeavor to give you notice of any such modification, suspension or discontinuance. You agree that, to the extent permitted by law, Crowdera will not be liable to you for any modification, suspension or discontinuance of the Services in accordance with these Terms of Service.</p>
    <h2>MODIFICATIONS TO SERVICES</h2>
    <p class="static-content-paragraph">The Platform may contain links to third-party websites ("External Sites"). These links are provided solely as a convenience to you and not as an endorsement by us of the content on such External Sites. The content of such External Sites is developed and provided by others. You should contact the site administrator or webmaster for those External Sites if you have any concerns regarding such links or any content located on such External Sites. We are not responsible for the content of any linked External Sites and do not make any representations regarding the content or accuracy of materials on such External Sites. You should take precautions when downloading files from all websites to protect your computer from viruses and other destructive programs. If you decide to access linked External Sites, you do so at your own risk.</p>
    <h2>PUBLIC DISPLAY OF DONATIONS</h2>
    <p class="static-content-paragraph">As a Donor, you have the option to publicly display your Donation for all to see, including on search engines (like Google and Yahoo). To keep the details of your Donation private, simply click the "Anonymous" checkbox during the Donation process. Please see our Privacy Policy for more information on the ways that we may collect, use, and store certain information about you and your use of the Services.</p>
    <h2>USE AND STORAGE PRACTICE</h2>
        <p class="static-content-paragraph">You acknowledge that Crowdera may establish general practices and limits concerning use of the Services, including without limitation the maximum period of time that data or other content will be retained by the Services and the maximum storage space that will be allotted on Crowdera's servers on your behalf. You agree that Crowdera has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded by the Services. You acknowledge that Crowdera reserves the right to terminate accounts or Campaigns that are inactive for an extended period of time, provided that Crowdera will use its commercially reasonable efforts to provide a Fundraiser with reasonable notice before terminating an inactive Campaign having a positive balance of Donations. You further acknowledge that Crowdera reserves the right to change these general practices and limits at any time, in its sole discretion. We will endeavor to give you notice of any such change where required by applicable law.</p>
    <h2>MOBILE SERVICES</h2>
    <p class="static-content-paragraph">The Services include certain services that are available via a mobile device, including (i) the ability to upload content to the Platform via a mobile device, (ii) the ability to browse the Platform from a mobile device and (iii) the ability to access certain features through an application downloaded and installed on a mobile device (collectively, the "Mobile Services"). To the extent you access the Services through a mobile device, your wireless service carrier's standard charges, data rates and other fees may apply. In addition, downloading, installing, or using certain Mobile Services may be prohibited or restricted by your carrier, and not all Mobile Services may work with all carriers or devices. By using the Mobile Services, you agree that we may communicate with you regarding Crowdera and other entities by SMS, MMS, text message or other electronic means to your mobile device and that certain information about your usage of the Mobile Services may be communicated to us. We shall comply with any additional requirements that may apply under local laws and regulations before communicating with you in this manner. In the event that you change or deactivate your mobile telephone number, you agree to promptly update your Crowdera account information to ensure that your messages are not sent to the person that acquires your old number.</p>
    <h1>DONORS TERMS & CONDITIONS</h1>
    <p class="static-content-paragraph">Any individual, entity or organization that registers as a user and donates funds through the Platform or the services (“donor”) represent and warrant to Crowdera that any information shared on the platform is true and that you are authorized to share that information. Donors are subject to the following additional warranties, terms and conditions:</p>
    <ol class="IN-TW-terms-use-ol-disc">
      <li>Contact Information mostly including Email and sometimes Phone is required for all Donors and depending on country specific requirements.</li>
      <li>Crowdera has partnered with WePay, PayU, Citrus, PayPal, and FirstGiving to make raising money and donating to charities easy and seamless. All transactions including designated donation and registration amounts and payment gateway fees, or any agreed upon charges will be charged to the credit or debit card or other payment method you use and will be processed by WePay, PayU, Citrus, PayPal, and FirstGiving. Crowdera is not liable for transaction disputes, errors, chargeback fees, or service downtime. By donating through the Platform you explicitly agree to indemnify, defend, and hold Crowdera and its respective officers, director, employees, agents, representatives, and affiliates harmless for any transaction claims, disputes, and any associated costs and/or expenses. You also agree to the terms laid by our payment gateway partners in their respective platforms as specified in the following links:</li>
      <ol class="IN-TW-terms-use-ol-circle">
      	<li>PayPal: https://www.paypal.com/ga/webapps/mpp/ua/useragreement-full</li>
      	<li>PayU: https://www.payumoney.com/termsandconditions.html</li>
      	<li>WePay: https://go.wepay.com/terms-of-service-us</li>
      	<li>Citrus:</li>
     </ol>
      <li>All donations are at your own risk. Please make sure that when you donate to a given individual, Event, Fundraiser or Nonprofit, you understand how your money will be used. When donating, only donate to those people or entities that you feel comfortable donating to or otherwise know and trust. Crowdera does not warrant that funds will be used for any particular purpose and is not responsible for any misuse of the funds by the Fundraiser.</li>
      <li>You agree that a certain minimum Donation amount may apply, and that all Donation payments are final and will not be refunded unless Fundraisers, in its sole discretion, agrees to issue a refund directly. Donors may have the option to donate recurring period Donations, and in electing to donate on a recurring basis, you, as a Donor (i) agree to promptly update your account information with any changes (for example, a change in your billing address or credit card expiration date) that may occur and to pay the Donation amount that you specify, and (ii) hereby authorize Crowdera to bill your payment instrument in advance on a periodic basis until you terminate such periodic payments, which can be done at any time through the Platform.</li>
	  <li>By donating money through the Platform, you represent and warrant that any donation you make is legal in your jurisdiction and that you are authorized to use the payment method you have selected. Donors are not permitted to impose restrictions on the use of donated funds by a Fundraiser. To the extent that a donation is made in response to an appeal for a particular program of a Fundraiser, or to the extent that a Donor purports to direct the use of donated funds by a Fundraiser, any such directions shall constitute non-binding recommendations only and the Fundraiser shall have full discretion to determine how all donated funds will be used.</li>
      <li>Crowdera makes no representation as to whether all or any portion of your donations, including, if any, transaction fees, are tax deductible or eligible for tax credits. Crowdera will have no liability for any claim by any federal, state, provincial, territorial, local or any other tax authority with respect to the characterization on any applicable tax return of any donation by you, any Crowdera user or any Nonprofit. You should consult your tax advisor as to the amount of your donation that is tax deductible or eligible for tax recognition, having regard to (among other things) the tax status of the recipient of any donation in any relevant jurisdiction, and particularly if you are awarded a gift or prize in connection with your donation.</li>
      <li>All charities in the U.S. have the option of using WePay or PayPal or FirstGiving to process donations made through the Platform. Charities in Canada and United Kingdom are required to use WePay or PayPal to process donations. Charities in India are required to use Citrus or PayU to process donations.</li>
      <li>The manner in which transactions are processed is explained below. </li>
    	<ol class="IN-TW-terms-use-ol-circle">
      	<li><b>FirstGiving</b> is a "donor advised fund," a 501(c)(3) organization that collects donations from donors and distributes such donations to 501(c)(3) organizations in good standing with the IRS as recommended by you. Donations made through FirstGiving are governed by the FirstGiving privacy notice and FirstGiving user agreement. All donations made through FirstGiving's credit card processing go directly from the donor to FirstGiving, and then to the Nonprofit of your choice, but FirstGiving will appear on your credit card statement. FirstGiving can be only used as payment processor by American 501(c)(3) registered nonprofits.</li>
      	<li><b>WePay.</b> When WePay processes a donation through the Platform, the donation will go directly from the donor to the nonprofit's WePay merchant account. Donations will appear on the donor's credit card statement under the name of the nonprofit to whom they donated.</li>
      	<li><b>Citrus.</b> When you make a donation through Citrus, Crowdera does not collect or store your credit card information. All donations processed through Citrus are disbursed via Citrus or Crowdera as agreed upon with the fundraisers and will be governed by the Citrus User Agreement and Citrus Privacy Notice.</li>
      	<li><b>PayU.</b> When you make a donation through PayU, Crowdera does not collect or store your credit card information. All donations processed through PayU are disbursed via Crowdera as agreed upon with the fundraisers and will be governed by the PayU User Agreement and PayU Privacy Notice.</li>
      </ol>
    </ol>
    <h1>FUNDRAISER TERMS & CONDITIONS</h1>
    <p class="static-content-paragraph">Fundraisers are people and organizations who set up and create fundraisers, donation pages, campaigns, scholarships, giving funds, charities, and other campaigns for social good (each called a "Campaign") on the Platform. Login is required for all Fundraisers, either through Facebook Connect, Google Plus, Twitter Connect, or pursuant to Section 6 below. Fundraisers can designate other people within their organization (number of other administrators limited by the subscription plan chosen by Fundraisers and subject to capabilities and functionality of the platform) to access the Platform and upload Campaign Content (as defined below). Fundraisers can do all the things that Visitors can do, and can: (i) create and set up a Campaign; (ii) upload updates, including blog posts, videos, photos, and other content regarding the Campaign (collectively, "Campaign Content"); (iii) connect their Campaign to their social networks and email lists; (iv) provide feedback; and (v) sign up for alerts and other notifications.</p>
    <h2>FUNDRAISER WARRANTIES</h2>
    <p class="static-content-paragraph">You, as a Fundraiser, represent, warrant, and covenant that (i) all information you provide in connection with a Campaign is accurate, complete, and not otherwise designed to mislead, defraud, or deceive any user; (ii) all Donations donated to your Campaign will be used solely as described in the materials that you post; (iii) you will comply with your jurisdiction’s applicable laws and regulations when you solicit funds, particularly, but not limited to, laws relating to your marketing and solicitation for your project; and (iv) to the extent you share with us any personal data of any third party for any purpose, including the names, email addresses and phone numbers of your personal contacts, you have the authority (including any necessary consents), as required under applicable law, to provide us with such personal data and allow us to use such personal data for the purposes for which you shared it with us. You authorize Crowdera, and Crowdera reserves the right to, provide information relating to your Campaign with donors and Fundraisers of your Campaign, and with law enforcement or to assist in any investigation.</p>
  	<h2>USER CONDUCT & GUIDELINES </h2>
  	    <p class="static-content-paragraph">Crowdera's community, like any community, functions best when its users follow a few simple rules. You are solely responsible for all Campaign descriptions, comments, videos, images, information, data, text, software, music, sound, photographs, graphics, messages or other materials ("content") that you upload, post, publish or display (hereinafter, "upload") or transmit or otherwise use via the Services. The following are examples of the kind of content and/or use that is illegal or prohibited by Crowdera. However, this list is not exhaustive and Crowdera reserves the right to investigate anyone by engaging public and private organizations, including, but not limited to collection agents, private investigators, and local, state, federal and applicable international agencies, and take appropriate action against anyone who, in Crowdera's sole discretion, violates any of the terms or spirit of these Terms of Service (or the principles described in our preamble hereto), including, without limitation, removing the offending content, suspending or terminating the account of such violators, stopping payments to any such Campaign, freezing or placing a hold on donated funds when Crowdera reasonably believes it to be required by applicable law, and reporting you to law enforcement authorities or otherwise taking appropriate legal action. Without limiting the foregoing, you agree to not use the Services to:</p>
  	<ol class="IN-TW-terms-use-ol-num">
  		 <li>establish or donate to any Campaign with the implicit or express purpose relating to any of the following:</li>
  		<ol class="IN-TW-terms-use-ol-circle">
      			<li>any activity that violates any law or governmental regulation;</li>
      	      	<li>content or campaigns that are fraudulent, misleading, inaccurate, dishonest, impossible or imitating any other person or fundraising campaign (whether on the Platform or not);</li>
      	      	<li>illegal drugs, narcotics, steroids, controlled substances or other products that present a risk to consumer safety or any related paraphernalia;</li>
      	      	<li>knives, explosives, ammunition, firearms, or other weaponry or accessories;</li>
      	      	<li>annuities, investments, equity or lottery contracts, lay-away systems, off-shore banking or similar transactions, money service businesses (including currency exchanges, check cashing or the like), debt collection or crypto-currencies;</li>
      	      	<li>gambling, gaming and/or any other activity with an entry fee and a prize, including, but not limited to casino games, sports betting, fantasy sports, horse or greyhound racing, lottery tickets, other ventures that facilitate gambling, games of skill or chance (whether or not it is legally defined as a lottery) or sweepstakes;</li>
      	      	<li>the promotion of hate, violence, harassment, discrimination, terrorism, or intolerance of any kind relating to race, ethnicity, national origin, religious affiliation, sexual orientation, sex, gender or gender identity, or serious disabilities or diseases;</li>
      	       <li>activities within, or involving countries, regions, governments, persons, or entities that are subject to U.S. and other economic sanctions under applicable law, unless such activities are expressly authorized by the appropriate governmental authority;</li>
      	       <li>ransom, human trafficking or exploitation;</li>
      	     <li>pornography or other sexual content;</li>
      	    <li>offensive, graphic, perverse or sensitive content;</li>
      	      <li>the defense or support of anyone alleged to be involved in criminal activity;</li>
      	       <li>offering monetary rewards, including gift cards;</li>
      	       <li>transactions for the sale of items before the seller has control or possession of the item;</li>
      	        <li>collection of payments on behalf of merchants by payment processors or otherwise;</li>
      	         <li>credit repair or debt settlement services.</li>
      </ol>
     <li>transmit or otherwise upload any content that (i) infringes any intellectual property or other proprietary rights of any party; (ii) you do not have a right to upload under any law or under contractual or fiduciary relationships; (iii) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; (iv) poses or creates a privacy or security risk to any person; (v) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, "junk mail," "spam," "chain letters," "pyramid schemes," "contests," "sweepstakes," or any other form of solicitation; or (vi) in the sole judgment of Crowdera, is objectionable or which restricts or inhibits any other person from using or enjoying the Services, or which may expose Crowdera or its users to any harm or liability of any type</li>
     <li>interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Services;</li>
     <li>harvest or collect email addresses or other contact information of other users from the Services by electronic or other means;</li>
  	</ol>
  	  	<h2>REGISTRATION PROCESS</h2>
  	<p class="static-content-paragraph">If Fundraisers or Donors do not log in to the Platform through Facebook Connect, Google, Linkedin or Twitter Connect, we will ask them to create an account, which includes a sign-in name ("Sign-In Name"), a password ("Password"), and perhaps certain additional information that will assist in authenticating their identity when they log in in the future, such as an e-mail address ("Unique Identifiers"). When creating their account, Fundraisers and Donors must provide true, accurate, current, and complete information. Each Sign-In Name and corresponding Password can be used by only one user. Fundraisers and Donors are solely responsible for the confidentiality and use of their Sign-In Name, Password, and Unique Identifiers, as well as for any use, misuse, or communications entered through the Platform using one or more of them. Fundraisers and Donors will promptly inform us of any need to deactivate a Password or Sign-In Name, or change any Unique Identifier. We reserve the right to delete or change any Password, Sign-In Name, or Unique Identifier at any time and for any reason. Crowdera will not be liable for any loss or damage caused by any unauthorized use of a Fundraiser's or Contributor’s account. You also agree to the terms laid by our payment gateway partners you choose to process your transactions.</p>
  	<h2>LICENCE TO USE/LIMITED LICENCE </h2>
  	<p class="static-content-paragraph">Crowdera grants Fundraiser a limited, non transferable, non exclusive, non-sublicensable, non-assignable and personal license to use “Funds raised through Crowdera”, “Powered by Crowdera”, and/or “via Crowdera” and/or Crowdera logo on campaign related collaterals, invoices/certificate of transaction concluded on Crowdera. </p>
  	<h1>NONPROFIT AND CHARITY FUNDRAISER TERMS</h1>
  	<h2>AMERICAN NONPROFITS AND CHARITIES TERMS</h2>
  	<p class="static-content-paragraph">American Charities or Nonprofits are the United States of America (“USA”)  based 501(c)(3) organizations in good standing with the Internal Revenue Service (IRS). As a Fundraiser using the Platfrom, 501(c)(3) Charities and NonProfits USA have the option of Platform to issue official donation receipts to the Donors through the Platform. Charities and Nonprofits that do so understand and acknowledge that the Nonprofit is responsible under section 501(c)3 of the Internal Revenue Code (“Code”), to ensure that all receipts are issued in compliance with applicable law.</p>
  	<h2>REGISTRATION PROCESS</h2>
  	<p class="static-content-paragraph">If Fundraisers or Donors do not log in to the Platform through Facebook Connect, Google, Linkedin or Twitter Connect, we will ask them to create an account, which includes a sign-in name ("Sign-In Name"), a password ("Password"), and perhaps certain additional information that will assist in authenticating their identity when they log in in the future, such as an e-mail address ("Unique Identifiers"). When creating their account, Fundraisers and Donors must provide true, accurate, current, and complete information. Each Sign-In Name and corresponding Password can be used by only one user. Fundraisers and Donors are solely responsible for the confidentiality and use of their Sign-In Name, Password, and Unique Identifiers, as well as for any use, misuse, or communications entered through the Platform using one or more of them. Fundraisers and Donors will promptly inform us of any need to deactivate a Password or Sign-In Name, or change any Unique Identifier. We reserve the right to delete or change any Password, Sign-In Name, or Unique Identifier at any time and for any reason. Crowdera will not be liable for any loss or damage caused by any unauthorized use of a Fundraiser's or Contributor’s account. You also agree to the terms laid by our payment gateway partners you choose to process your transactions.</p>
  	<ol class="IN-TW-terms-use-ol-disc">
      	<li>USA based Charities and Nonprofits intending to use the Platform to issue donation receipts must provide Crowdera with the following information (i) Current head office address, phone number as recorded with the Internal Revenue Service; (ii) EIN number of the organization and the deductible status; (iii)Reproducible jpeg image of signature of authorized representative that can be affixed to official donation receipts; and must notify Crowdera immediately of any changes to this information.</li>
      	<li>A description and the fair market value of any and all perks, rewards or other benefits provided to Donors in respect of Donations to the Nonprofit through the Crowdera Platform, which shall be used to determine the eligible amount of the gift for receipting purposes. For greater certainty, the value of any such benefits shall be subtracted from the fair market value of property gifted to the Nonprofit to determine the eligible amount of the gift.</li>
      	<li>Platform will rely wholly on the information provided by the Nonprofit or its representatives in order to prepare official donation receipts, as well as information supplied to it by Donors when making Donations. Crowdera is not responsible to verify any information provided to it by the Nonprofit, any representative of the Nonprofit, or any Donor. The Nonprofit acknowledges this and agrees that Crowdera shall not be responsible for any incorrect information included on an official donation receipt, or for any tax or regulatory consequences resulting from the provision of incorrect information by the Nonprofit, any representative of the Nonprofit, or any Donor.</li>
      	<li>All 501 c 3 registered charities  and Nonprofits are subject to record-keeping obligations under IRS. Each Nonprofit is responsible to ensure that it maintains such records as are required under applicable law. This includes a requirement to maintain copies of all official donation receipts issued and records to verify donations received. Each Nonprofit can also access donation reports and copies of all official donation receipts issued on that Nonprofit’s behalf by logging on Crowdera’s secure Platform, and can print these documents manually. Nonprofits can also access reconciliation reports from Payment Gateway (WePay, PayPal or FirstGiving) pursuant to their respective Terms of Service.</li>
     </ol>
    <h2>CANADIAN CHARITIES TERMS</h2>
  	<p class="static-content-paragraph">Canadian Charities are the charitable organizations approved by Canada Revenue Agency (CRA) as Canadian Charity. Canadian Non Profit Organizations (NPO) are  the same as Canadian Charities and cannot issue official donation receipts for income tax purposes.</p>
  	<ol class="IN-TW-terms-use-ol-disc">
      	<li>Canadian Charities intending to use the Crowdera Platform to issue donation receipts  must provide Crowdera with the following information (i) Current head office address, phone number as recorded with the CRA; (ii) Registration number as designated by CRA; (iii) Name of representative duly authorized by the Charity to sign official donation receipts; (iv)Reproducible jpeg image of signature of authorized representative that can be affixed to official donation receipts; and must notify Crowdera immediately of any changes to this information.</li>
      	<li>A description and the fair market value of any and all perks, rewards or other benefits provided to Donors in respect of Donations to the Charity through the Crowdera Platform, which shall be used to determine the eligible amount of the gift for receipting purposes. For greater certainty, the value of any such benefits shall be subtracted from the fair market value of property gifted to the Charity to determine the eligible amount of the gift.</li>
      	<li>Platform will rely wholly on the information provided by the Charity or its representatives in order to prepare official donation receipts, as well as information supplied to it by Donors when making Donations. Crowdera is not responsible to verify any information provided to it by the Charity, any representative of the Charity, or any Donor. The Charity acknowledges this and agrees that Crowdera shall not be responsible for any incorrect information included on an official donation receipt, or for any tax or regulatory consequences resulting from the provision of incorrect information by the Charity, any representative of the Charity, or any Donor.</li>
      	<li>All Canadian registered charities are subject to record-keeping obligations under CRA. Each Charity is responsible to ensure that it maintains such records as are required under applicable law. This includes a requirement to maintain copies of all official donation receipts issued and records to verify donations received. Each Charity can also access donation reports and copies of all official donation receipts issued on that Charity’s behalf by logging on Crowdera’s secure site, and can print these documents manually. Canadian Charities can also access reconciliation reports from Payment Gateway (WePay or PayPal) pursuant to their respective Terms of Service..</li>
        <li>A Charity on behalf of which Crowdera issues official donation receipts may at any time request a copy of the form of receipt being issued and may direct Crowdera to revise the form of receipt as necessary to ensure compliance with applicable law</li>
    </ol>
    <h2>INDIAN NOT FOR PROFIT ORGANIZATIONS TERMS</h2>
  	<p class="static-content-paragraph">Indian Nonprofits generally known as Non Governmental Organizations (NGOs), Trusts, Societies, and Section 8 Companies are the charitable organizations approved by either by Indian Central or State Government Bodies under any of the following regulations: (i)Income Tax Act (1961); (ii)Public Trusts Acts of various states; (iii)Societies Registration Act (1860); (iv)Indian Companies Act (2013) Section 8; (v)Foreign Contribution Regulation Act (2010); and (vi)Maharashtra Value Added Tax Act (2002), as amended by Act No. IX of 2005</p>
  	<ol class="IN-TW-terms-use-ol-disc">
      	<li>Indian Nonprofits understand and acknowledge that the Nonprofit is responsible under the Income Tax Act, 1961  to ensure that all receipts are issued in compliance with applicable law. Indian Nonprofits intending to use the Platform to issue donation receipts must provide Crowdera with the following information and must notify Crowdera immediately of any changes to the information below:</li>
      	<ol class="IN-TW-terms-use-ol-circle">
      		  <li>Current head office address as appears on registration certificate;</li>
      		    <li>Name of representative duly authorized by the Nonprofit to sign official donation receipts;</li>
      		    <li>Reproducible jpeg image of signature of authorized representative that can be affixed to official donation receipts;</li>
      		    <li>Registration date and registration number;</li>
      		     <li>Active and working phone number</li>
      		    <li>PAN card number of the Nonprofit</li>
      		   <li>Status of the organization and % Exempt</li>
      		  <li>A description and the fair market value of any and all perks, rewards or other benefits provided to Donors in respect of Donations to the Nonprofit through the Crowdera Platform, which shall be used to determine the eligible amount of the gift for receipting purposes. For greater certainty, the value of any such benefits shall be subtracted from the fair market value of property gifted to the Nonprofit to determine the eligible amount of the gift.</li>
      	</ol>
      	<li>Platform will rely wholly on the information provided by the Nonprofit or its representatives in order to prepare official donation receipts, as well as information supplied to it by Donors when making Donations. Crowdera is not responsible to verify any information provided to it by the Nonprofit, any representative of the Nonprofit, or any Donor. The Nonprofit acknowledges this and agrees that Crowdera shall not be responsible for any incorrect information included on an official donation receipt, or for any tax or regulatory consequences resulting from the provision of incorrect information by the Nonprofit, any representative of the Nonprofit, or any Donor.</li>
      	<li>All Indian Nonprofits are subject to record-keeping obligations under their respective Regulatory Authorities. Each Nonprofit is responsible to ensure that it maintains such records as are required under applicable law. This includes a requirement to maintain copies of all official donation receipts issued and records to verify donations received. Each Nonprofit can also access donation reports and copies of all official donation receipts issued on that Nonprofit’s behalf by logging on Crowdera’s secure Platform, and can print these documents manually. Nonprofits can also access reconciliation reports from Payment Gateway (Citrus and PayU) pursuant to their respective Terms of Service.</li>
      	<li>A Nonprofit on behalf of which Crowdera issues official donation receipts may at any time request a copy of the form of receipt being issued and may direct Crowdera to revise the form of receipt as necessary to ensure compliance with applicable law</li>
        <li>Indian Nonprofits agree that by listing their fundraiser on Crowdera, they abide by various laws applicable including but not limited to the Income Tax Act, 1961, the Foreign Contributions Regulations Act, 2010, the Information Technology Act, 2000 as well as all rules and regulations made under the respective laws and as amended from time to time. </li>
      </ol>  
       <h2>UNITED KINGDOM CHARITIES TERMS</h2>
        	<p class="static-content-paragraph">United Kingdom (UK) Charity is a Charitable Organization registered with the Charities Commission in England and Wales, the Office of the Scottish Charity Regulator or for charities in Northern Ireland the Northern Irish Charity Commission and Her Majesty’s Revenue and Customs (HMRC); or a charity without a requirement to register with one of the bodies referred to above, but treated as a charity by HMRC for tax purposes</p>
            	<ol class="IN-TW-terms-use-ol-disc">
            	<li>A description and the fair market value of any and all perks, rewards or other benefits provided to Donors in respect of Donations to the Charity through the Crowdera Platform, which shall be used to determine the eligible amount of the gift for receipting purposes. For greater certainty, the value of any such benefits shall be subtracted from the fair market value of property gifted to the Charity to determine the eligible amount of the gift.</li>
      		    <li>Platform will rely wholly on the information provided by the Charity or its representatives in order to prepare official donation receipts, as well as information supplied to it by Donors when making Donations. Crowdera is not responsible to verify any information provided to it by the Charity, any representative of the Charity, or any Donor. The Charity acknowledges this and agrees that Crowdera shall not be responsible for any incorrect information included on an official donation receipt, or for any tax or regulatory consequences resulting from the provision of incorrect information by the Charity, any representative of the Charity, or any Donor.</li>
      		    <li>All UK Charities are subject to record-keeping obligations under with one of the bodies referred to above. Each Charity is responsible to ensure that it maintains such records as are required under applicable law. This includes a requirement to maintain copies of all official donation receipts issued and records to verify donations received. Each Charity can also access donation reports and copies of all official donation receipts issued on that Charity’s behalf by logging on Crowdera’s secure site, and can print these documents manually. Canadian Charities can also access reconciliation reports from Payment Gateway (WePay or PayPal) pursuant to their respective Terms of Service..</li>
      		    <li>A Charity on behalf of which Crowdera issues official donation receipts may at any time request a copy of the form of receipt being issued and may direct Crowdera to revise the form of receipt as necessary to ensure compliance with applicable law.</li>
      </ol>
      <h2>OTHER GLOBAL CHARITIES TERMS & CONDITIONS</h2>
   		<p class="static-content-paragraph">Crowdera will not be able to send official donation receipts on behalf of all other global nonprofits and charitable organizations from countries other than UK, USA, India and Canada. However, all other nonprofits will will be considered as regular fundraisers on the platform and will be able to use all other platform features regulated by this universal terms of service.</p>
      <h1>FEES AND PAYMENTS</h1>
      <p class="static-content-paragraph">Although there is no commission or fee charged as a percentage of each Donation, Crowdera offers paid subscription services to use value added features and value added services offered by the platform. Please see our Fees section for details. You acknowledge and agree that your Payment Method may be charged by one of our affiliated entities, Crowdera Inc., or Crowdera Ventures India Pvt Ltd. If, during your purchase, your payment was identified as being processed in the United States and any other country other than India, your transaction will be processed by Crowdera Inc., 101 Jefferson Dr. Menlo Park, CA (USA) 94025; if your payment was identified as being processed in India, your transaction will be processed by Crowdera Ventures India Pvt. Ltd., 206 Sankalp Nagar Wathoda Nagpur Maharashtra (INDIA) 440009.</p>
      <p class="static-content-paragraph"><b>Commission Free Platform.</b> Fundraisers can use our platform free as we do not take any commissions or percentage from the funds raised. Our free plan features are laid out on the pricing page.</p>
            <p class="static-content-paragraph"><b>Crowdera Subscription Fee.</b> However, some fundraisers pay us a subscription fee for using our value added features and services. Our subscription fees are laid out on the pricing page.</p>
            <p class="static-content-paragraph"><b>Payment Gateway Transaction Fee.</b> Fundraisers pay a transaction fee to the selected payment partner from FirstGiving, WePay, PayPal, Citrus, and PayU to use their services. Transaction fees are laid out on the Fee page.</p>
            <p class="static-content-paragraph"><b>Refunds</b>
 			Crowdera is not responsible for handling or communicating a Fundraiser's refund policy or processing refunds, including for any errors processing a refund, the failure to provide a refund, the failure of a Fundraiser to communicate about a refund, or any chargebacks related to a refund. Simply put, you have to deal with the Fundraiser concerning a refund and Fundraiser agree to deal exclusively with donor concerning refunds. </p>
            <p class="static-content-paragraph"><b>General Terms, Including Automatic Renewal Terms</b><br />
          	You agree to pay any and all prices and fees due for Services purchased or obtained at this Platform at the time you order the Services.  All prices and fees are non-refundable unless otherwise expressly noted in the Refund Policy section below, even if your Services are suspended, terminated, or transferred prior to the end of the Services term.  Crowdera expressly reserves the right to change or modify its prices and fees at any time, and such changes or modifications shall be posted online at this Platform and effective immediately without need for further notice to you.  If you have purchased or obtained Services for a period of months or years, changes or modifications in prices and fees shall be effective when the Services in question come up for renewal. </p>
            <p class="static-content-paragraph" \>IN ORDER TO ENSURE THAT YOU DO NOT EXPERIENCE AN INTERRUPTION OR LOSS OF SERVICES, ALL SERVICES ARE OFFERED ON AUTOMATIC RENEWAL.  EXCEPT FOR REASONS DESCRIBED BELOW IN THIS SECTION, AUTOMATIC RENEWAL AUTOMATICALLY RENEWS THE APPLICABLE SERVICE UPON EXPIRATION OF THE THEN CURRENT TERM FOR A RENEWAL PERIOD EQUAL IN TIME TO THE MOST RECENT SERVICE PERIOD.  FOR EXAMPLE, IF YOUR LAST SERVICE PERIOD IS FOR ONE YEAR, YOUR RENEWAL PERIOD WILL TYPICALLY BE FOR ONE YEAR.  HOWEVER, IN THE EVENT RENEWAL WITH THE PAYMENT METHOD ON FILE FAILS, CROWDERA MAY ATTEMPT TO RENEW THE APPLICABLE SERVICE FOR A PERIOD LESS THAN THE ORIGINAL SUBSCRIPTION PERIOD TO THE EXTENT NECESSARY FOR THE TRANSACTION TO SUCCEED. 
			UNLESS YOU DISABLE THE AUTOMATIC RENEWAL OPTION, CROWDERA WILL AUTOMATICALLY RENEW THE APPLICABLE SERVICE WHEN IT COMES UP FOR RENEWAL AND WILL TAKE PAYMENT FROM THE PAYMENT METHOD YOU HAVE ON FILE WITH CROWDERA AT CROWDERA’S THEN CURRENT RATES, WHICH YOU ACKNOWLEDGE AND AGREE MAY BE HIGHER OR LOWER THAN THE RATES FOR THE ORIGINAL SERVICE PERIOD.  IF YOU DO NOT WISH FOR ANY SERVICE TO AUTOMATICALLY RENEW, YOU MAY ELECT TO CANCEL RENEWAL, IN WHICH CASE, YOUR SERVICES WILL TERMINATE UPON EXPIRATION OF THE THEN CURRENT TERM, UNLESS YOU MANUALLY RENEW YOUR SERVICES PRIOR TO THAT DATE (IN WHICH CASE THE SERVICES WILL AGAIN BE SET TO AUTOMATIC RENEWAL).  IN OTHER WORDS, SHOULD YOU ELECT TO CANCEL YOUR SERVICE AND FAIL TO MANUALLY RENEW YOUR SERVICES BEFORE THEY EXPIRE, YOU MAY EXPERIENCE AN INTERRUPTION OR LOSS OF SERVICES, AND CROWDERA SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY REGARDING THE SAME.
			IN ADDITION, CROWDERA MAY PARTICIPATE IN “RECURRING BILLING PROGRAMS” OR “ACCOUNT UPDATER SERVICES” SUPPORTED BY YOUR CREDIT CARD PROVIDER (AND ULTIMATELY DEPENDENT ON YOUR BANK’S PARTICIPATION).  IF WE ARE UNABLE TO SUCCESSFULLY CHARGE YOUR EXISTING PAYMENT METHOD, YOUR CREDIT CARD PROVIDER (OR YOUR BANK) MAY NOTIFY US OF UPDATES TO YOUR CREDIT CARD NUMBER AND/OR EXPIRATION DATE, OR THEY MAY AUTOMATICALLY CHARGE YOUR NEW CREDIT CARD ON OUR BEHALF WITHOUT NOTIFICATION TO US.  IN ACCORDANCE WITH RECURRING BILLING PROGRAM REQUIREMENTS, IN THE EVENT THAT WE ARE NOTIFIED OF AN UPDATE TO YOUR CREDIT CARD NUMBER AND/OR EXPIRATION DATE, CROWDERA WILL AUTOMATICALLY UPDATE YOUR PAYMENT PROFILE ON YOUR BEHALF. CROWDERA MAKES NO GUARANTEES THAT WE WILL REQUEST OR RECEIVE UPDATED CREDIT CARD INFORMATION. YOU ACKNOWLEDGE AND AGREE THAT IT IS YOUR SOLE RESPONSIBILITY TO MODIFY AND MAINTAIN YOUR ACCOUNT SETTINGS, INCLUDING BUT NOT LIMITED TO (I) CANCELLING SERVICE AND (II) ENSURING YOUR ASSOCIATED PAYMENT METHOD(S) ARE CURRENT AND VALID.  FURTHER, YOU ACKNOWLEDGE AND AGREE THAT YOUR FAILURE TO DO SO, MAY RESULT IN THE INTERRUPTION OR LOSS OF SERVICES, AND CROWDERA SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY REGARDING THE SAME. </p>
            <p class="static-content-paragraph">Crowdera may offer product-level pricing in various currencies; however, transaction processing is supported only in U.S. dollars and a select number of the currency options displayed on this platform ("Supported Currency" or “Supported Currencies”). If the currency selected is a Supported Currency, then the transaction will be processed in the Supported Currency and the pricing displayed during the checkout process will be the actual amount processed and submitted to your bank for payment. If the currency selected is not a Supported Currency, then the transaction will be processed in U.S. dollars and the pricing displayed during the checkout process will be an estimated conversion price at the time of purchase. In either case (whether the currency selected is a Supported Currency or not), if the transaction is processed in a currency that differs from the currency of your bank account, you may be charged exchange rate conversion fees by your bank.  In addition, due to time differences between (i) the time you complete the checkout process, (ii) the time the transaction is processed, and (iii) the time the transaction posts to your bank statement, the conversion rates may fluctuate, and Crowdera makes no representations or warranties that (a) the amount submitted to your bank for payment will be the same as the amount posted to your bank statement (in the case of a Supported Currency) or (b) the estimated conversion price will be the same as either the amount processed or the amount posted to your bank statement (in the case of a non-Supported Currency), and you agree to waive any and all claims based upon such discrepancies (including any and all claims for a refund based on the foregoing). In addition, regardless of the selected currency, you acknowledge and agree that you may be charged Value Added Tax ("VAT"), Goods and Services Tax ("GST"), or other localized fees and/or taxes, based on your bank and/or the country indicated in your billing address section.</p> 
  	 <h1>OTHER IMPORTANT TERMS AND CONDITIONS </h1>
  	 <h2>THIRD PARTY WEBSITES/SERVICES</h2>
  	      <p class="static-content-paragraph">The Services may provide or facilitate, or third parties may provide, links or other access to other sites, services and resources on the Internet. Crowdera has no control over such sites, services and resources and Crowdera is not responsible for and does not endorse such sites, services and resources. You further acknowledge and agree that Crowdera will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods or services available on or through any such site, service or resource. Any dealings you have with third parties found while using the Services are between you and the third party, and you agree that Crowdera is not liable for any loss or claim that you may have against any such third party.</p>
  	 <h2>USE OF COMMUNICATION SERVICES</h2>
  	    <p class="static-content-paragraph">The Platform may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other message or communication facilities designed to enable you to communicate with the public at large or with a group (collectively, "Communication Services"), you agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service.</p>
   	    <p class="static-content-paragraph">By way of example, and not as a limitation, you agree that when using a Communication Service, you will not: defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others; publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information; upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents; upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another's computer; advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages; conduct or forward surveys, contests, pyramid schemes or chain letters; download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner; falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded, restrict or inhibit any other user from using and enjoying the Communication Services; violate any code of conduct or other guidelines which may be applicable for any particular Communication Service; harvest or otherwise collect information about others, including e-mail addresses, without their consent; violate any applicable laws or regulations.</p>
   		<p class="static-content-paragraph">By way of example, and not as a limitation, you agree that when using a Communication Service, you will not: defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others; publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information; upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents; upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another's computer; advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages; conduct or forward surveys, contests, pyramid schemes or chain letters; download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner; falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded, restrict or inhibit any other user from using and enjoying the Communication Services; violate any code of conduct or other guidelines which may be applicable for any particular Communication Service; harvest or otherwise collect informatCrowdera has no obligation to monitor the Communication Services. However, Crowdera reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion. Crowdera reserves the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever.</p>
    	<p class="static-content-paragraph">Crowdera reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in Crowdera's sole discretion.</p>
     	<p class="static-content-paragraph">Always use caution when giving out any personally identifying information about yourself or your children in any Communication Service. Crowdera does not control or endorse the content, messages or information found in any Communication Service and, therefore, Crowdera specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized Crowdera spokespersons, and their views do not necessarily reflect those of Crowdera.</p>
      	<p class="static-content-paragraph">Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination. You are responsible for adhering to such limitations if you upload the materials.</p>
 	 <h2>MATERIALS PROVIDED TO CROWDERA  OR POSTED ON PLATFORM</h2>
 	  	 <p class="static-content-paragraph">Crowdera does not claim ownership of the materials you provide to www.gocrowdera.com (including feedback and suggestions) or post, upload, input or submit to any Crowdera Platform or our associated services (collectively "Submissions"). However, by posting, uploading, inputting, providing or submitting your Submission you are granting Crowdera, our affiliated companies and necessary sublicensees permission to use your Submission in connection with the operation of their Internet businesses including, without limitation, the rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Submission; and to publish your name in connection with your Submission.</p>
   	    <p class="static-content-paragraph">No compensation will be paid with respect to the use of your Submission, as provided herein. Crowdera is under no obligation to post or use any Submission you may provide and may remove any Submission at any time in Crowdera's sole discretion.</p>
   		<p class="static-content-paragraph">By posting, uploading, inputting, providing or submitting your Submission you warrant and represent that you own or otherwise control all of the rights to your Submission as described in this section including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the Submissions.</p>
     <h2>ADDITIONAL TERMS, POLICIES, & AGREEMENTS</h2>
    	
    	<p class="static-content-paragraph">Your use of the Platform, or any of the services or features accessible therein, constitutes that you have read, understand, acknowledge and agree to be bound by this Agreement, along with the following policies and the applicable product agreements, which are incorporated herein by reference:</p>
     	<p class="static-content-paragraph"><b>Partnership:</b> Users may create a "Partner Page" on Crowdera Platform to link their brand with one or more Campaigns. If Users create a Partner Page, Users also agree to the Partner Terms.</p>
     	<p class="static-content-paragraph"><b>Privacy Policy.</b> You accept our Privacy Policy, which you may view in full by <a href="/privacypolicy">clicking here.</a></p>
     	<p class="static-content-paragraph"><b>India Terms of Service.</b> If you are an Indian resident or accessing our platform from India, you accept our Terms of Services agreement made for Indian users, which you may view in full by <a href="/in/tos">clicking here.</a></p>
     	<p class="static-content-paragraph"><b>Availability of Service.</b> As the provider of the Platform., we reserve the right to discontinue (i) the Platform., in whole or in part, (ii) any features or services provided by or through the Platform, or (iii) your account with the Platform, for any or no reason, without notice to you.</p>
     	<p class="static-content-paragraph"><b>Successors and Assigns.</b> This Agreement shall be binding upon and inure to the benefit of the parties hereto and their respective heirs, successors and assigns.</p>
     	<p class="static-content-paragraph"><b>Availability of Service.</b> As the provider of the Platform., we reserve the right to discontinue (i) the Platform., in whole or in part, (ii) any features or services provided by or through the Platform, or (iii) your account with the Platform, for any or no reason, without notice to you.</p>
     	<p class="static-content-paragraph"><b>No Third Party Beneficiaries.</b> Nothing in this Agreement shall be deemed to confer any third-party rights or benefits</p>
     	<p class="static-content-paragraph"><b>For India Residents ONLY. </b>You expressly agree that: (i) Crowdera (or its service provider) may contact you by phone in order to resolve your complaint or dispute, or your current service or billing issue; and (ii) in order to resolve such complaint, dispute or issue, Crowdera may use and may disclose to its service provider the following information: call recordings, customer name, phone number(s) and contact preferences, tenure of your relationship with Crowdera, products used, and information about the nature of your complaint, dispute, or service issue.</p>
     	<p class="static-content-paragraph"><b>Compliance with Local Laws. </b>Crowdera makes no representation or warranty that the content available on this Platform or the Services found at this Platform are appropriate in every country or jurisdiction, and access to this Platform or the Services found at this Platform from countries or jurisdictions where its content is illegal is prohibited.  Users who choose to access this Platform or the Services found at this Platform are responsible for compliance with all local laws, rules and regulations.</p>
     	<p class="static-content-paragraph"><b>Notification Procedures.</b> Users agree Crowdera may provide notifications to such User via email, written or hard copy notice, or through conspicuous posting of such notice on our Platform. Users may opt out of certain means of notification or to receive certain notifications.</p>
     	<p class="static-content-paragraph"><b>Entire agreement/ severability. </b>Users agree Crowdera may provide notifications to such User via email, written or hard copy notice, or through conspicuous posting of such notice on our Platform. Users may opt out of certain means of notification or to receive certain notifications.</p>
    <h2>DISCLAIMER OF REPRESENTATIONS AND WARRANTIES</h2>
     	<p class="static-content-paragraph">YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT YOUR USE OF THIS Platform AND THE SERVICES FOUND AT THIS Platform SHALL BE AT YOUR OWN RISK AND THAT THIS Platform AND THE SERVICES FOUND AT THIS Platform ARE PROVIDED “AS IS”, “AS AVAILABLE” AND “WITH ALL FAULTS”. Crowdera, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND ALL THIRD PARTY SERVICE PROVIDERS DISCLAIM ALL WARRANTIES, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. Crowdera, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS MAKE NO REPRESENTATIONS OR WARRANTIES ABOUT (I) THE ACCURACY, COMPLETENESS, OR CONTENT OF THIS SITE, (II) THE ACCURACY, COMPLETENESS, OR CONTENT OF ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, AND/OR (III) THE SERVICES FOUND AT THIS Platform OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, AND Crowdera ASSUMES NO LIABILITY OR RESPONSIBILITY FOR THE SAME.IN ADDITION, YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT NO ORAL OR WRITTEN INFORMATION OR ADVICE PROVIDED BY Crowdera, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS (INCLUDING WITHOUT LIMITATION ITS CALL CENTER OR CUSTOMER SERVICE REPRESENTATIVES), AND THIRD PARTY SERVICE PROVIDERS  WILL (I) CONSTITUTE LEGAL OR FINANCIAL ADVICE OR (II) CREATE A WARRANTY OF ANY KIND WITH RESPECT TO THIS Platform OR THE SERVICES FOUND AT THIS SITE, AND USERS SHOULD NOT RELY ON ANY SUCH INFORMATION OR ADVICE.THE FOREGOING DISCLAIMER OF REPRESENTATIONS AND WARRANTIES SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, AND SHALL SURVIVE ANY TERMINATION OR EXPIRATION OF THIS AGREEMENT OR YOUR USE OF THIS Platform OR THE SERVICES FOUND AT THIS Platform.</p>
     <h2>LIMITATION OF LIABILITY</h2>
     	<p class="static-content-paragraph">IN NO EVENT SHALL Crowdera, ITS OFFICERS, DIRECTORS, EMPLOYEES,  AGENTS, AND ALL THIRD PARTY SERVICE PROVIDERS, BE LIABLE TO YOU OR ANY OTHER PERSON OR ENTITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING ANY THAT MAY RESULT FROM (I) THE ACCURACY, COMPLETENESS, OR CONTENT OF THIS SITE, (II) THE ACCURACY, COMPLETENESS, OR CONTENT OF ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (III) THE SERVICES FOUND AT THIS Platform OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (IV) PERSONAL INJURY OR PROPERTY DAMAGE OF ANY NATURE WHATSOEVER, (V) THIRD-PARTY CONDUCT OF ANY NATURE WHATSOEVER, (VI) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL CONTENT, PERSONAL INFORMATION, FINANCIAL INFORMATION OR OTHER INFORMATION AND DATA STORED THEREIN, (VII) ANY INTERRUPTION OR CESSATION OF SERVICES TO OR FROM THIS Platform OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (VIII) ANY VIRUSES, WORMS, BUGS, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR FROM THIS Platform OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (IX) ANY USER CONTENT OR CONTENT THAT IS DEFAMATORY, HARASSING, ABUSIVE, HARMFUL TO MINORS OR ANY PROTECTED CLASS, PORNOGRAPHIC, “X-RATED”, OBSCENE OR OTHERWISE OBJECTIONABLE, AND/OR (X) ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF THIS Platform OR THE SERVICES FOUND AT THIS SITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL OR EQUITABLE THEORY, AND WHETHER OR NOT Crowdera IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
IN ADDITION, YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THIS Platform OR THE SERVICES FOUND AT THIS Platform MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE SUCH CAUSE OF ACTION SHALL BE PERMANENTLY BARRED.
IN ADDITION, YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT IN NO EVENT SHALL Crowdera’S TOTAL AGGREGATE LIABILITY EXCEED $10,000.00 U.S. DOLLARS.
THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, AND SHALL SURVIVE ANY TERMINATION OR EXPIRATION OF THIS AGREEMENT OR YOUR USE OF THIS Platform OR THE SERVICES FOUND AT THIS Platform.
</p>
    <h2>INDEMNIFICATION</h2>
     	<p class="static-content-paragraph">You agree to protect, defend, indemnify and hold harmless Crowdera and its officers, directors, employees, agents, and third party service providers from and against any and all claims, demands, costs, expenses, losses, liabilities and damages of every kind and nature (including, without limitation, reasonable attorneys’ fees) imposed upon or incurred by Crowdera directly or indirectly arising from (i) your use of and access to this Platform or the Services found at this Site; (ii) your violation of any provision of this Agreement or the policies or agreements which are incorporated herein; and/or (iii) your violation of any third-party right, including without limitation any intellectual property or other proprietary right.  The indemnification obligations under this section shall survive any termination or expiration of this Agreement or your use of this Platform or the Services found at this Platform.</p>
    <h2>TERMINATION/ACCESS RESTRICTION</h2>
     	<p class="static-content-paragraph">Crowdera reserves the right, in its sole discretion, to terminate your access to the Platform and the related services or any portion thereof at any time, without notice. To the maximum extent permitted by law, this agreement is governed by the laws of the State of Delaware and you hereby consent to the exclusive jurisdiction and venue of courts in Delaware in all disputes arising out of or relating to the use of the Platform. Use of the Platform is unauthorized in any jurisdiction that does not give effect to all provisions of these Terms, including, without limitation, this section.</p>
        <p class="static-content-paragraph">You agree that no joint venture, partnership, employment, or agency relationship exists between you and Crowdera as a result of this agreement or use of the Platform. Crowdera's performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of Crowdera's right to comply with governmental, court and law enforcement requests or requirements relating to your use of the Platform or information provided to or gathered by Crowdera with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect.</p>
        <p class="static-content-paragraph">Unless otherwise specified herein, this agreement constitutes the entire agreement between the user and Crowdera with respect to the Platform and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and Crowdera with respect to the Platform. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish to the parties that this agreement and all related documents be written in English.</p>
    
    <h2>DISCONTINUED SERVICES; END OF LIFE POLICY</h2>
     	<p class="static-content-paragraph">Crowdera reserves the right to cease offering or providing any of the Services at any time, for any or no reason, and without prior notice. Although Crowdera makes great effort to maximize the lifespan of all its Services, there are times when a Service we offer will be discontinued or reach its End-of-Life ("EOL"). If that is the case, that product or service will no longer be supported by Crowdera, in any way, effective on the EOL date.</p>
     	<p class="static-content-paragraph">Notice and Migration. In the event that any Service we offer has reached or will reach EOL, we will attempt to notify you thirty or more days in advance of the EOL date. It is your responsibility to take all necessary steps to replace the Service by migrating to a new Service before the EOL date, or by entirely ceasing reliance on said Service before the EOL date. In either case, Crowdera will either offer a comparable Service for you to migrate to for the remainder of the term of your purchase, a prorated in-store credit, or a prorated refund, to be determined by Crowdera in its sole and absolute discretion. Crowdera may, with or without notice to you, migrate you to the most up-to-date version of the Service, if available. You agree to take full responsibility for any and all loss or damage arising from any such migration.</p>
     	<p class="static-content-paragraph">No Liability. Crowdera will not be liable to you or any third party for any modification, suspension, or discontinuance of any of the Services we may offer or facilitate access to.</p>
    <h2>U.S. EXPORT LAWS</h2>
     	<p class="static-content-paragraph">This Platform and the Services found at this Platform are subject to the export laws, restrictions, regulations and administrative acts of the United States Department of Commerce, Department of Treasury Office of Foreign Assets Control (“OFAC”), State Department, and other United States authorities (collectively, “U.S. Export Laws”).  Users shall not use the Services found at this Platform to collect, store or transmit any technical information or data that is controlled under U.S. Export Laws.  Users shall not export or re-export, or allow the export or re-export of, the Services found at this Platform in violation of any U.S. Export Laws.  None of the Services found at this Platform may be downloaded or otherwise exported or re-exported (i) into (or to a national or resident of) any country with which the United States has embargoed trade; or (ii) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Commerce Department's Denied Persons List, or any other denied parties lists under U.S. Export Laws.  By using this Platform and the Services found at this Site, you agree to the foregoing and represent and warrant that you are not a national or resident of, located in, or under the control of, any restricted country; and you are not on any denied parties list; and you agree to comply with all U.S. Export Laws (including “anti-boycott”, “deemed export” and “deemed re-export” regulations).  If you access this Platform or the Services found at this Platform from other countries or jurisdictions, you do so on your own initiative and you are responsible for compliance with the local laws of that jurisdiction, if and to the extent those local laws are applicable and do not conflict with U.S. Export Laws.  If such laws conflict with U.S. Export Laws, you shall not access this Platform or the Services found at this Platform.  The obligations under this section shall survive any termination or expiration of this Agreement or your use of this Platform or the Services found at this platform.</p>
    <h2>CLASS ACTION WAIVER</h2>
     	<p class="static-content-paragraph">Any arbitration under these Terms and Conditions will take place on an individual basis; class arbitrations and class/representative/collective actions are not permitted. THE PARTIES AGREE THAT A PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN EACH'S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PUTATIVE CLASS, COLLECTIVE AND/ OR REPRESENTATIVE PROCEEDING, SUCH AS IN THE FORM OF A PRIVATE ATTORNEY GENERAL ACTION AGAINST THE OTHER. Further, unless both you and Employer agree otherwise, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of a representative or class proceeding.</p>
 	<h2>SECURITY</h2>
     	<p class="static-content-paragraph">Crowdera takes reasonable precautions to protect our users' information. Your account information is located on a secured server behind a firewall. Because email and instant messaging are not recognized as secure communications, we request that you not send private information to us by email or instant messaging services. Although we allow you to set privacy setting that limit access to your information, please be aware that no security measures are perfect or 100% effective. We cannot control the actions of other users with whom you may choose to share your pages and information. Even after removal, copies of Materials may remain viewable in cached and archived pages or if other users have copied or stored your Materials. If you have any questions about the security of Crowdera Application, please contact us at privacy@gocrowdera.com.</p>
	<h2>ENGLISH LANGUAGE</h2>
     	<p class="static-content-paragraph">This Agreement, along with all policies and the applicable product agreements identified above and incorporated herein by reference (collectively, the “Agreement”), is executed in the English language. To the extent any translation is provided to you, it is provided for convenience purposes only, and in the event of any conflict between the English and translated version, where permitted by law, the English version will control and prevail. Where the translated version is required to be provided to you and is to be considered binding by law (i) both language versions shall have equal validity, (ii) each party acknowledges that it has reviewed both language versions and that they are substantially the same in all material respects, and (iii) in the event of any discrepancy between these two versions, the translated version may prevail, provided that the intent of the Parties has been fully taken into consideration. </p>
	<h2>DMCA</h2>
     	<p class="static-content-paragraph">Crowdera respects the intellectual property rights of others and attempts to comply with all relevant laws. We will review all claims of copyright infringement received and remove any Content or Campaign Content deemed to have been posted or distributed in violation of any such laws. Our designated agent under the Digital Millennium Copyright Act (the "Act") for the receipt of any Notification of Claimed Infringement which may be given under that Act is as follows:</p>
	        <p class="static-content-paragraph">Crowdera InC<br />
      Attention: DMCA<br />
      101 Jefferson Dr<br />
      Menlo Park CA 94025<br>
    <u class="termofuse-style"><small><a href="mailto:contact@crowdera.co">contact@crowdera.co</a></small></u></p>
	    <p class="static-content-paragraph">If you believe that your work has been copied on the Platform in a way that constitutes copyright infringement, please provide our agent with notice in accordance with the requirements of the Act, including: (i) a description of the copyrighted work that has been infringed and the specific location on the Platform where such work is located; (ii) a description of the location of the original or an authorized copy of the copyrighted work; (iii) your address, telephone number and e-mail address; (iv) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; (v) a statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf; and (vi) an electronic or physical signature of the owner of the copyright or the person authorized to act on behalf of the owner of the copyright interest.</p>
		<p class="static-content-paragraph"><b><i>Our failure to act on or enforce any provision of the Agreement shall not be construed as a waiver of that provision or any other provision in this Agreement. No waiver shall be effective against us unless made in writing, and no such waiver shall be construed as a waiver in any other or subsequent instance. Except as expressly agreed by us and you in writing, this Agreement constitutes the entire Agreement between you and us with respect to the subject matter, and supersedes all previous or contemporaneous agreements, whether written or oral, between the parties with respect to the subject matter. The section headings are provided merely for convenience and shall not be given any legal import. This Agreement will inure to the benefit of our successors, assigns, licensees, and sublicensees.</i></b></p>
	<h2>CONTACT US</h2>
	<p class="static-content-paragraph">Crowdera welcomes your questions or comments regarding the Terms:<br />
	    <b>Crowdera InC</b><br />
      101 Jefferson Dr<br />
      Menlo Park, California 94025<br>
    <u class="termofuse-style"><b>Email Address:</b><a href="mailto:contact@crowdera.co">contact@crowdera.co</a></u></p>
	
    	
  </div>
</div>
</body>
</html>
